## Canalização

| N_Bloco   |   Uplink_Inicial |   Uplink_Final |   Downlink_Inicial |   Downlink_Final | Faixa     |
|:----------|-----------------:|---------------:|-------------------:|-----------------:|:----------|
| 1         |            451   |          451.1 |              461   |            461.1 | 451-468   |
| 2         |            451.1 |          451.2 |              461.1 |            461.2 | 451-468   |
| 3         |            451.2 |          451.3 |              461.2 |            461.3 | 451-468   |
| 4         |            451.3 |          451.4 |              461.3 |            461.4 | 451-468   |
| 5         |            451.4 |          451.5 |              461.4 |            461.5 | 451-468   |
| 6         |            451.5 |          451.6 |              461.5 |            461.6 | 451-468   |
| 7         |            451.6 |          451.7 |              461.6 |            461.7 | 451-468   |
| 8         |            451.7 |          451.8 |              461.7 |            461.8 | 451-468   |
| 9         |            451.8 |          451.9 |              461.8 |            461.9 | 451-468   |
| 10        |            451.9 |          452   |              461.9 |            462   | 451-468   |
| 11        |            452   |          452.1 |              462   |            462.1 | 451-468   |
| 12        |            452.1 |          452.2 |              462.1 |            462.2 | 451-468   |
| 13        |            452.2 |          452.3 |              462.2 |            462.3 | 451-468   |
| 14        |            452.3 |          452.4 |              462.3 |            462.4 | 451-468   |
| 15        |            452.4 |          452.5 |              462.4 |            462.5 | 451-468   |
| 16        |            452.5 |          452.6 |              462.5 |            462.6 | 451-468   |
| 17        |            452.6 |          452.7 |              462.6 |            462.7 | 451-468   |
| 18        |            452.7 |          452.8 |              462.7 |            462.8 | 451-468   |
| 19        |            452.8 |          452.9 |              462.8 |            462.9 | 451-468   |
| 20        |            452.9 |          453   |              462.9 |            463   | 451-468   |
| 21        |            453   |          453.1 |              463   |            463.1 | 451-468   |
| 22        |            453.1 |          453.2 |              463.1 |            463.2 | 451-468   |
| 23        |            453.2 |          453.3 |              463.2 |            463.3 | 451-468   |
| 24        |            453.3 |          453.4 |              463.3 |            463.4 | 451-468   |
| 25        |            453.4 |          453.5 |              463.4 |            463.5 | 451-468   |
| 26        |            453.5 |          453.6 |              463.5 |            463.6 | 451-468   |
| 27        |            453.6 |          453.7 |              463.6 |            463.7 | 451-468   |
| 28        |            453.7 |          453.8 |              463.7 |            463.8 | 451-468   |
| 29        |            453.8 |          453.9 |              463.8 |            463.9 | 451-468   |
| 30        |            453.9 |          454   |              463.9 |            464   | 451-468   |
| 31        |            454   |          454.1 |              464   |            464.1 | 451-468   |
| 32        |            454.1 |          454.2 |              464.1 |            464.2 | 451-468   |
| 33        |            454.2 |          454.3 |              464.2 |            464.3 | 451-468   |
| 34        |            454.3 |          454.4 |              464.3 |            464.4 | 451-468   |
| 35        |            454.4 |          454.5 |              464.4 |            464.5 | 451-468   |
| 36        |            454.5 |          454.6 |              464.5 |            464.6 | 451-468   |
| 37        |            454.6 |          454.7 |              464.6 |            464.7 | 451-468   |
| 38        |            454.7 |          454.8 |              464.7 |            464.8 | 451-468   |
| 39        |            454.8 |          454.9 |              464.8 |            464.9 | 451-468   |
| 40        |            454.9 |          455   |              464.9 |            465   | 451-468   |
| 41        |            455   |          455.1 |              465   |            465.1 | 451-468   |
| 42        |            455.1 |          455.2 |              465.1 |            465.2 | 451-468   |
| 43        |            455.2 |          455.3 |              465.2 |            465.3 | 451-468   |
| 44        |            455.3 |          455.4 |              465.3 |            465.4 | 451-468   |
| 45        |            455.4 |          455.5 |              465.4 |            465.5 | 451-468   |
| 46        |            455.5 |          455.6 |              465.5 |            465.6 | 451-468   |
| 47        |            455.6 |          455.7 |              465.6 |            465.7 | 451-468   |
| 48        |            455.7 |          455.8 |              465.7 |            465.8 | 451-468   |
| 49        |            455.8 |          455.9 |              465.8 |            465.9 | 451-468   |
| 50        |            455.9 |          456   |              465.9 |            466   | 451-468   |
| 51        |            456   |          456.1 |              466   |            466.1 | 451-468   |
| 52        |            456.1 |          456.2 |              466.1 |            466.2 | 451-468   |
| 53        |            456.2 |          456.3 |              466.2 |            466.3 | 451-468   |
| 54        |            456.3 |          456.4 |              466.3 |            466.4 | 451-468   |
| 55        |            456.4 |          456.5 |              466.4 |            466.5 | 451-468   |
| 56        |            456.5 |          456.6 |              466.5 |            466.6 | 451-468   |
| 57        |            456.6 |          456.7 |              466.6 |            466.7 | 451-468   |
| 58        |            456.7 |          456.8 |              466.7 |            466.8 | 451-468   |
| 59        |            456.8 |          456.9 |              466.8 |            466.9 | 451-468   |
| 60        |            456.9 |          457   |              466.9 |            467   | 451-468   |
| 61        |            457   |          457.1 |              467   |            467.1 | 451-468   |
| 62        |            457.1 |          457.2 |              467.1 |            467.2 | 451-468   |
| 63        |            457.2 |          457.3 |              467.2 |            467.3 | 451-468   |
| 64        |            457.3 |          457.4 |              467.3 |            467.4 | 451-468   |
| 65        |            457.4 |          457.5 |              467.4 |            467.5 | 451-468   |
| 66        |            457.5 |          457.6 |              467.5 |            467.6 | 451-468   |
| 67        |            457.6 |          457.7 |              467.6 |            467.7 | 451-468   |
| 68        |            457.7 |          457.8 |              467.7 |            467.8 | 451-468   |
| 69        |            457.8 |          457.9 |              467.8 |            467.9 | 451-468   |
| 70        |            457.9 |          458   |              467.9 |            468   | 451-468   |
| 1         |            703   |          708   |              758   |            763   | 703-803   |
| 2         |            708   |          713   |              763   |            768   | 703-803   |
| 3         |            713   |          718   |              768   |            773   | 703-803   |
| 4         |            718   |          723   |              773   |            778   | 703-803   |
| 5         |            723   |          728   |              778   |            783   | 703-803   |
| 6         |            728   |          733   |              783   |            788   | 703-803   |
| 7         |            733   |          738   |              788   |            793   | 703-803   |
| 8         |            738   |          743   |              793   |            798   | 703-803   |
| 9         |            743   |          748   |              798   |            803   | 703-803   |
| 1         |            819   |          824   |              864   |            869   | 819-894   |
| 2         |            824   |          829   |              869   |            874   | 819-894   |
| 3         |            829   |          834   |              874   |            879   | 819-894   |
| 4         |            834   |          839   |              879   |            884   | 819-894   |
| 5         |            839   |          844   |              884   |            889   | 819-894   |
| 6         |            844   |          849   |              889   |            894   | 819-894   |
| 1         |            898.5 |          901   |              943.5 |            946   | 898.5-960 |
| 2         |            905   |          907.5 |              950   |            952.5 | 898.5-960 |
| 3         |            907.5 |          910   |              952.5 |            955   | 898.5-960 |
| 4         |            910   |          912.5 |              955   |            957.5 | 898.5-960 |
| 5         |            912.5 |          915   |              957.5 |            960   | 898.5-960 |
| 1         |           1710   |         1715   |             1805   |           1810   | 1710-1880 |
| 2         |           1715   |         1720   |             1810   |           1815   | 1710-1880 |
| 3         |           1720   |         1725   |             1815   |           1820   | 1710-1880 |
| 4         |           1725   |         1730   |             1820   |           1825   | 1710-1880 |
| 5         |           1730   |         1735   |             1825   |           1830   | 1710-1880 |
| 6         |           1735   |         1740   |             1830   |           1835   | 1710-1880 |
| 7         |           1740   |         1745   |             1835   |           1840   | 1710-1880 |
| 8         |           1745   |         1750   |             1840   |           1845   | 1710-1880 |
| 9         |           1750   |         1755   |             1845   |           1850   | 1710-1880 |
| 10        |           1755   |         1760   |             1850   |           1855   | 1710-1880 |
| 11        |           1760   |         1765   |             1855   |           1860   | 1710-1880 |
| 12        |           1765   |         1770   |             1860   |           1865   | 1710-1880 |
| 13        |           1770   |         1775   |             1865   |           1870   | 1710-1880 |
| 14        |           1775   |         1780   |             1870   |           1875   | 1710-1880 |
| 15        |           1780   |         1785   |             1875   |           1880   | 1710-1880 |
| 1         |           1920   |         1925   |             2110   |           2115   | 1920-2170 |
| 2         |           1925   |         1930   |             2115   |           2120   | 1920-2170 |
| 3         |           1930   |         1935   |             2120   |           2125   | 1920-2170 |
| 4         |           1935   |         1940   |             2125   |           2130   | 1920-2170 |
| 5         |           1940   |         1945   |             2130   |           2135   | 1920-2170 |
| 6         |           1945   |         1950   |             2135   |           2140   | 1920-2170 |
| 7         |           1950   |         1955   |             2140   |           2145   | 1920-2170 |
| 8         |           1955   |         1960   |             2145   |           2150   | 1920-2170 |
| 9         |           1960   |         1965   |             2150   |           2155   | 1920-2170 |
| 10        |           1965   |         1970   |             2155   |           2160   | 1920-2170 |
| 11        |           1970   |         1975   |             2160   |           2165   | 1920-2170 |
| 12        |           1975   |         1980   |             2165   |           2170   | 1920-2170 |
| 1         |           1980   |         1985   |             2170   |           2175   | 1980-2200 |
| 2         |           1985   |         1990   |             2175   |           2180   | 1980-2200 |
| 3         |           1990   |         1995   |             2180   |           2185   | 1980-2200 |
| 4         |           1995   |         2000   |             2185   |           2190   | 1980-2200 |
| 5         |           2000   |         2005   |             2190   |           2195   | 1980-2200 |
| 6         |           2005   |         2010   |             2195   |           2200   | 1980-2200 |
| 1         |           2500   |         2505   |             2620   |           2625   | 2500-2690 |
| 2         |           2505   |         2510   |             2625   |           2630   | 2500-2690 |
| 3         |           2510   |         2515   |             2630   |           2635   | 2500-2690 |
| 4         |           2515   |         2520   |             2635   |           2640   | 2500-2690 |
| 5         |           2520   |         2525   |             2640   |           2645   | 2500-2690 |
| 6         |           2525   |         2530   |             2645   |           2650   | 2500-2690 |
| 7         |           2530   |         2535   |             2650   |           2655   | 2500-2690 |
| 8         |           2535   |         2540   |             2655   |           2660   | 2500-2690 |
| 9         |           2540   |         2545   |             2660   |           2665   | 2500-2690 |
| 10        |           2545   |         2550   |             2665   |           2670   | 2500-2690 |
| 11        |           2550   |         2555   |             2670   |           2675   | 2500-2690 |
| 12        |           2555   |         2560   |             2675   |           2680   | 2500-2690 |
| 13        |           2560   |         2565   |             2680   |           2685   | 2500-2690 |
| 14        |           2565   |         2570   |             2685   |           2690   | 2500-2690 |
| 15        |           2570   |         2575   |             2570   |           2575   | 2500-2690 |
| 16        |           2575   |         2580   |             2575   |           2580   | 2500-2690 |
| 17        |           2580   |         2585   |             2580   |           2585   | 2500-2690 |
| 18        |           2585   |         2590   |             2585   |           2590   | 2500-2690 |
| 19        |           2590   |         2595   |             2590   |           2595   | 2500-2690 |
| 20        |           2595   |         2600   |             2595   |           2600   | 2500-2690 |
| 21        |           2600   |         2605   |             2600   |           2605   | 2500-2690 |
| 22        |           2605   |         2610   |             2605   |           2610   | 2500-2690 |
| 23        |           2610   |         2615   |             2610   |           2615   | 2500-2690 |
| 24        |           2615   |         2620   |             2615   |           2620   | 2500-2690 |
| C-3       |            nan   |          nan   |             2570   |           2576   | 2570-2618 |
| C-4       |            nan   |          nan   |             2582   |           2588   | 2570-2618 |
| D-3       |            nan   |          nan   |             2576   |           2582   | 2570-2618 |
| D-4       |            nan   |          nan   |             2588   |           2594   | 2570-2618 |
| E-1       |            nan   |          nan   |             2594   |           2600   | 2570-2618 |
| E-2       |            nan   |          nan   |             2606   |           2612   | 2570-2618 |
| F-1       |            nan   |          nan   |             2600   |           2606   | 2570-2618 |
| F-2       |            nan   |          nan   |             2612   |           2618   | 2570-2618 |

## Processamento

In [ ]:
import sys
from pathlib import Path
import pandas as pd
import numpy as np

In [ ]:
sys.path.insert(0, str(Path().cwd().parent))
%load_ext autoreload
%autoreload 2

In [ ]:
from extracao.format import parse_bw
from extracao.updates import split_designacao

In [ ]:
COLS_SMP = {
    "NumAto": "Num_Ato",
    "NumFistel": "Fistel",
    "NomeEntidade": "Entidade",
    "SiglaUf": "UF",
    "NumEstacao": "Número_Estação",
    "CodMunicipio": "Código_Município",
    "DataValidade": "Validade_RF",
    "FreqInicialMHz": "Frequência_Inicial",
    "FreqCentralMHz": "Frequência_Central",
    "FreqTxMHz": "Frequência_Transmissão",
    "FreqRxMHz": "Frequência_Recepção",
    "FreqFinalMHz": "Frequência_Final",
    "formId": "Tipo_Estação",
    "Tecnologia": "Tecnologia",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "DesignacaoEmissao": "Designação_Emissão",
    "PotenciaTransmissorWatts": "Potência(W)",
    "CodTipoAntena": "Cod_TipoAntena",
    "Polarizacao": "Polarização",
    "RaioAntena": "Raio_Antena",
    "GanhoAntena": "Ganho_Antena",
    "FrenteCostaAntena": "FC_Antena",
    "AnguloMeiaPotenciaAntena": "Ang_MP_Antena",
    "AnguloElevacao": "Ângulo_Elevação",
    "Azimute": "Azimute",
    "AlturaAntena": "Altura_Antena",
    "PerdasAcessorias": "Perdas_Acessorias",
}

DTYPE_SMP = {
    "NumAto": "category",
    "NumFistel": "category",
    "NomeEntidade": "category",
    "SiglaUf": "category",
    "NumEstacao": "string",
    "CodMunicipio": "category",
    "DataValidade": "category",
    "FreqInicialMHz": "category",
    "FreqCentralMHz": "category",
    "FreqFinalMHz": "category",
    "FreqTxMHz": "category",
    "FreqRxMHz": "category",
    "formId": "category",
    "Tecnologia": "category",
    "Latitude": "float",
    "Longitude": "float",
    "DesignacaoEmissao": "category",
    "PotenciaTransmissorWatts": "float",
    "CodTipoAntena": "category",
    "Polarizacao": "category",
    "RaioAntena": "float",
    "GanhoAntena": "float",
    "FrenteCostaAntena": "float",
    "AnguloMeiaPotenciaAntena": "float",
    "AnguloElevacao": "float",
    "Azimute": "float",
    "AlturaAntena": "float",
    "PerdasAcessorias": "float",
}

In [ ]:
folder = Path.cwd().parent / 'dados'

In [ ]:
df = pd.read_parquet(folder / 'smp_formated.parquet.gzip')

In [ ]:
df = df.rename(columns=COLS_SMP)

In [ ]:
df = split_designacao(df)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1946684 entries, 0 to 1946610
Data columns (total 29 columns):
 #   Column                  Dtype
---  ------                  -----
 0   Num_Ato                 string
 1   Validade_RF             string
 2   Fistel                  string
 3   Entidade                string
 4   Número_Estação          string
 5   Latitude                string
 6   Longitude               string
 7   Frequência_Inicial      string
 8   Frequência_Final        string
 9   Frequência_Central      string
 10  Código_Município        string
 11  UF                      string
 12  Potência(W)             string
 13  Cod_TipoAntena          string
 14  Polarização             string
 15  Raio_Antena             string
 16  Ganho_Antena            string
 17  FC_Antena               string
 18  Ang_MP_Antena           string
 19  Ângulo_Elevação         string
 20  Azimute                 string
 21  Altura_Antena           string
 22  Perdas_Acessorias       string
 23  Tipo_Estação            string
 24  Tecnologia              string
 25  Frequência_Transmissão  string
 26  Frequência_Recepção     string
 27  Largura_Emissão(kHz)    string
 28  Classe_Emissão          string
dtypes: string(29)
memory usage: 445.6 MB

A Frequência Central possui muitas lacunas nos dados, a frequência de transmissão será o dado utilizado.

In [ ]:
df[df.Frequência_Central.isna()].shape

(591400, 29)

In [ ]:
df[df.Frequência_Central == df.Frequência_Transmissão].shape

(297944, 29)

In [ ]:
df[df.Frequência_Final == df.Frequência_Transmissão].shape

(626866, 29)

In [ ]:
df[df.Frequência_Inicial == df.Frequência_Transmissão].shape

(24, 29)

Criar canais de Transmissão - Downlink

In [ ]:
bw = df['Largura_Emissão(kHz)'].astype('float') / 2000 # Unidade em kHz
df['Início_Canal_Down'] = df.Frequência_Transmissão.astype(float) - bw 
df['Fim_Canal_Down'] = df.Frequência_Transmissão.astype(float) + bw
# df['Início_Canal_Up'] = df.Frequência_Recepção.astype(float) - bw 
# df['Fim_Canal_Up'] = df.Frequência_Recepção.astype(float) + bw

In [ ]:
df.groupby(['Frequência_Transmissão'], as_index=False).size().sort_values('size', ascending=False)

   Frequência_Transmissão   size
98                  874.5  92135
61                 2160.0  87642
91                  788.0  69379
79                 2680.0  69357
55                 2140.0  63948
..                    ...    ...
99                  879.7      6
46                 1960.0      3
84                 3640.0      3
67                25400.0      2
70                25600.0      2

[115 rows x 2 columns]

Eliminar colunas que não serão utilizadas

In [ ]:
df.drop(['Frequência_Inicial', 'Frequência_Central', 'Frequência_Final'], axis=1, inplace=True)

Como vamos agrupar diversas estações baseadas em um subconjunto de colunas, vamos ordenar os dados de forma crescente pelo número da estação. Assim ao agruparmos diversos registros num só, o número da estação desse agrupamento será a estação licenciada mais antiga do grupo, em outras palavras, será mantido o número da estação menor por conta do ordenamento.

In [ ]:
df['Número_Estação'] = df['Número_Estação'].astype(int) 
df = df.sort_values('Número_Estação', ignore_index=True)
df = df.astype('string')

In [ ]:
subset = ['UF', 'Código_Município', 'Fistel', 'Frequência_Transmissão', 'Largura_Emissão(kHz)', 'Classe_Emissão']

É preciso eliminar dados vazios em qualquer das colunas que serão agrupadas, do contrário há um desalinhamento ao tentar juntar a contagem dos dados agregados.

In [ ]:
df.dropna(subset=subset, axis=0, inplace=True)

In [ ]:
df_sub = df[~df.duplicated(subset=subset, keep="first")].reset_index(drop=True)

In [ ]:
df_sub['Multiplicidade'] = df.groupby(subset, sort=False).size().values

In [ ]:
df_sub.sample(10)

,Num_Ato,Validade_RF,Fistel,Entidade,Número_Estação,Latitude,Longitude,Código_Município,UF,Potência(W),...,Perdas_Acessorias,Tipo_Estação,Tecnologia,Frequência_Transmissão,Frequência_Recepção,Largura_Emissão(kHz),Classe_Emissão,Início_Canal_Down,Fim_Canal_Down,Multiplicidade
140401,16952008.0,2023-04-30,50409889580,CLARO S.A.,1014584350,-23.82247,-51.66603,4113106,PR,62.8,...,0.0,base,WCDMA,2130.0,1940.0,5000.0,D7W,2127.5,2132.5,6
58203,35352011,2023-04-30,50409889580,CLARO S.A.,685053148,-15.85472,-58.46528,5106828,MT,40.0,...,0,base,LTE,1825.0,1820.0,5000.0,G7W,1822.5,1827.5,3
5472,35312011,2023-04-30,50409146447,TELEFONICA BRASIL S.A.,5138221,-22.901397,-49.627597,3546405,SP,40.0,...,0.0,base,LTE,1867.5,1772.5,5000.0,G7W,1865.0,1870.0,15
94786,17012008.0,2023-04-30,50409146366,TELEFONICA BRASIL S.A.,691481954,-16.490472,-52.696278,5107198,MT,40.0,...,0.0,base,WCDMA,2160.0,1970.0,5000.0,G7W,2157.5,2162.5,3
85726,149592017.0,2032-12-18,50409889580,CLARO S.A.,690732368,-23.0936,-52.7868,4100905,PR,40.0,...,0,base,LTE,1880.0,1872.5,7500.0,G7W,1876.25,1883.75,3
116509,27882022,2028-11-29,50409146285,TELEFONICA BRASIL S.A.,1001813534,-21.70139,-42.96361,3140209,MG,40.0,...,0.0,base,WCDMA,885.0,840.0,5000.0,G7W,882.5,887.5,3
16422,97812014,2029-12-08,50409428698,TIM S/A,422351695,-12.14778,-45.0,2903201,BA,40,...,,base,LTE,783.0,778.0,5000.0,G7W,780.5,785.5,3
6686,59072012,2032-12-22,50409146285,TELEFONICA BRASIL S.A.,5206200,-22.969203,-42.027906,3300258,RJ,46.1,...,0.0,base,LTE,2680.0,2560.0,20000.0,G7W,2670.0,2690.0,17
25743,46642011,2028-04-15,50409889580,CLARO S.A.,511472641,-29.4,-51.945,4301008,RS,20.0,...,0,base,GSM,1880.0,1870.0,200.0,G7W,1879.9,1880.1,6
8898,41662008,2023-08-05,50409146447,TELEFONICA BRASIL S.A.,323763456,-23.322465,-46.236818,3546801,SP,63.5,...,0.0,base,WCDMA,874.5,829.5,5000.0,G7W,872.0,877.0,21

In [ ]:
df_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142579 entries, 0 to 142578
Data columns (total 29 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Num_Ato                 142579 non-null  string
 1   Validade_RF             142579 non-null  string
 2   Fistel                  142579 non-null  string
 3   Entidade                142579 non-null  string
 4   Número_Estação          142579 non-null  string
 5   Latitude                142579 non-null  string
 6   Longitude               142579 non-null  string
 7   Código_Município        142579 non-null  string
 8   UF                      142579 non-null  string
 9   Potência(W)             142579 non-null  string
 10  Cod_TipoAntena          142579 non-null  string
 11  Polarização             142579 non-null  string
 12  Raio_Antena             54888 non-null   string
 13  Ganho_Antena            142579 non-null  string
 14  FC_Antena               142579 non-null  string
 15  Ang_MP_Antena           142579 non-null  string
 16  Ângulo_Elevação         142579 non-null  string
 17  Azimute                 142579 non-null  string
 18  Altura_Antena           142579 non-null  string
 19  Perdas_Acessorias       142579 non-null  string
 20  Tipo_Estação            142579 non-null  string
 21  Tecnologia              142579 non-null  string
 22  Frequência_Transmissão  142579 non-null  string
 23  Frequência_Recepção     142578 non-null  string
 24  Largura_Emissão(kHz)    142579 non-null  string
 25  Classe_Emissão          142579 non-null  string
 26  Início_Canal_Down       142579 non-null  string
 27  Fim_Canal_Down          142579 non-null  string
 28  Multiplicidade          142579 non-null  int64
dtypes: int64(1), string(28)
memory usage: 31.5 MB

Lendo e formatando o arquivo de canais do serviço SMP, construído à partir da  [Resolução nº 757, de 08 de novembro de 2022](https://informacoes.anatel.gov.br/legislacao/resolucoes/2022/1760-resolucao-757)

In [ ]:
canais = pd.read_excel(folder / 'canalização_smp.xlsx', dtype = 'string')
canais

,N_Bloco,Uplink_Inicial,Uplink_Final,Downlink_Inicial,Downlink_Final,Largura_Bloco(MHz),Offset,Faixa,Tecnologia
0,1,451,451.1,461,461.1,0.10000000000002274,10,451-468,UHF
1,2,451.1,451.2,461.1,461.2,0.0999999999999659,10,451-468,UHF
2,3,451.2,451.3,461.2,461.3,0.10000000000002274,10,451-468,UHF
3,4,451.3,451.4,461.3,461.4,0.0999999999999659,10,451-468,UHF
4,5,451.4,451.5,461.4,461.5,0.10000000000002274,10,451-468,UHF
...,...,...,...,...,...,...,...,...,...
142,20,2595,2600,2595,2600,5,0,2500-2690,GSM|LTE
143,21,2600,2605,2600,2605,5,0,2500-2690,GSM|LTE
144,22,2605,2610,2605,2610,5,0,2500-2690,GSM|LTE
145,23,2610,2615,2610,2615,5,0,2500-2690,GSM|LTE
146,24,2615,2620,2615,2620,5,0,2500-2690,GSM|LTE

In [ ]:
canais[['Downlink_Inicial', 'Downlink_Final']] = canais[['Downlink_Inicial', 'Downlink_Final']].astype(float)
canais[['Uplink_Inicial', 'Uplink_Final']] = canais[['Uplink_Inicial', 'Uplink_Final']].astype(float)
canais = canais.sort_values(['Downlink_Inicial'], ignore_index=True)
canais['N_Bloco'] = canais['N_Bloco'].str.strip()
canais['Faixa'] = canais['Faixa'].str.strip()

In [ ]:
df_sub[['Início_Canal_Down', 'Fim_Canal_Down']] = df_sub[['Início_Canal_Down', 'Fim_Canal_Down']].astype(float)

In [ ]:
conjunto_de_canais = df_sub.groupby(['Início_Canal_Down', 'Fim_Canal_Down']).size().to_frame('Total').reset_index()
conjunto_de_canais.sort_values('Total', ascending=False, inplace=True, ignore_index=True)
conjunto_de_canais

     Início_Canal_Down  Fim_Canal_Down  Total
0             872.0000        877.0000   4863
1             783.0000        793.0000   4071
2            2157.5000       2162.5000   3810
3             773.0000        783.0000   3652
4            2137.5000       2142.5000   2991
..                 ...             ...    ...
398          2665.0005       2664.9995      1
399          2665.7550       2674.2450      1
400          2649.8000       2660.2000      1
401          1817.5000       1827.5000      1
402          2355.0000       2385.0000      1

[403 rows x 3 columns]

In [ ]:
# from tqdm.auto import tqdm
# for row in tqdm(conjunto_de_canais.itertuples()):
#     for subset in canais.groupby('Faixa'):
#         canal, canais_subset = subset
#         begin = canais_subset[(row.Início_Canal >= canais_subset['Downlink_Inicial']) & (row.Início_Canal < canais_subset['Downlink_Final'])]
#         end = canais_subset[(row.Fim_Canal > canais_subset['Downlink_Inicial']) & (row.Fim_Canal <= canais_subset['Downlink_Final'])]
#         if not begin.empty and not end.empty:
#             blocos = '|'.join(canais_subset.loc[begin.index[0]:end.index[-1], 'N_Bloco'])
#             conjunto_de_canais.loc[row.Index, ['Blocos', 'Faixas']] = blocos, canal
#             break

In [ ]:
# from tqdm.auto import tqdm
# for row in tqdm(conjunto_de_canais.itertuples()):
#     begin = canais[(row.Início_Canal >= canais['Downlink_Inicial']) & (row.Início_Canal < canais['Downlink_Final'])]
#     end = canais[(row.Fim_Canal > canais['Downlink_Inicial']) & (row.Fim_Canal <= canais['Downlink_Final'])]
#     if not begin.empty and not end.empty:
#         blocos = '|'.join(canais.loc[begin.index[0]:end.index[0], 'N_Bloco'])
#         faixas = '|'.join(canais.loc[begin.index[0]:end.index[0], 'Faixa'].unique())
#         conjunto_de_canais.loc[row.Index, ['Blocos', 'Faixas']] = blocos, faixas

In [ ]:
from tqdm.auto import tqdm
conjunto_de_canais['Intervalo_Canal'] = 'Inválido'
for row in tqdm(conjunto_de_canais.itertuples()):
    interval = canais[(row.Início_Canal_Down < canais['Downlink_Final']) & (row.Fim_Canal_Down > canais['Downlink_Inicial'])]
    faixa = 'Downlink'
    if interval.empty:
        interval = canais[(row.Início_Canal_Down < canais['Uplink_Final']) & (row.Fim_Canal_Down > canais['Uplink_Inicial'])]
        faixa = 'Uplink'
    else:
        down = ' | '.join(interval[['Downlink_Inicial', 'Downlink_Final']].apply(lambda x: f'{x[0]}-{x[1]}', axis=1))
        faixas = ' | '.join(interval.Faixa.unique())
        offset = ' | '.join(interval.Offset.unique())
        conjunto_de_canais.loc[row.Index, ['Blocos_Downlink', 'Faixas', 'Intervalo_Canal', 'Offset']] = down, faixas, faixa, offset

0it [00:00, ?it/s]

In [ ]:
# conjunto_de_canais['Intervalo_Canal_Up'] = 'Inválido'
# for row in tqdm(conjunto_de_canais.itertuples()):
#     interval = canais[(row.Início_Canal_Up < canais['Uplink_Final']) & (row.Fim_Canal_Up > canais['Uplink_Inicial'])]
#     faixa = 'Uplink'
#     if interval.empty:
#         interval = canais[(row.Início_Canal_Up < canais['Downlink_Final']) & (row.Fim_Canal_Up > canais['Downlink_Inicial'])]
#         faixa = 'Downlink'
#     else:
#         up = ' | '.join(interval[['Uplink_Inicial', 'Uplink_Final']].apply(lambda x: f'{x[0]}-{x[1]}', axis=1))
#         faixas = ' | '.join(interval.Faixa.unique())
#         conjunto_de_canais.loc[row.Index, ['Blocos_Uplink', 'Faixas_Uplink', 'Intervalo_Canal_Up']] = up, faixas, faixa

0it [00:00, ?it/s]

In [ ]:
conjunto_de_canais = conjunto_de_canais[['Início_Canal_Down', 'Fim_Canal_Down', 'Blocos_Downlink', 'Faixas', 'Intervalo_Canal', 'Offset']]
# conjunto_de_canais.to_excel(folder / 'canais2canalização.xlsx', index=False)

In [ ]:
conjunto_de_canais

,Início_Canal_Down,Fim_Canal_Down,Blocos_Downlink,Faixas,Intervalo_Canal,Offset,Total
0,872.0000,877.0000,869.0-874.0 | 874.0-879.0,819-894,Downlink,45,4863
1,783.0000,793.0000,783.0-788.0 | 788.0-793.0,703-803,Downlink,55,4071
2,2157.5000,2162.5000,2155.0-2160.0 | 2160.0-2165.0,1920-2170,Downlink,190,3810
3,773.0000,783.0000,773.0-778.0 | 778.0-783.0,703-803,Downlink,55,3652
4,2137.5000,2142.5000,2135.0-2140.0 | 2140.0-2145.0,1920-2170,Downlink,190,2991
...,...,...,...,...,...,...,...
398,2665.0005,2664.9995,NaN,NaN,Inválido,NaN,1
399,2665.7550,2674.2450,2665.0-2670.0 | 2670.0-2675.0,2500-2690,Downlink,120,1
400,2649.8000,2660.2000,2645.0-2650.0 | 2650.0-2655.0 | 2655.0-2660.0 ...,2500-2690,Downlink,120,1
401,1817.5000,1827.5000,1815.0-1820.0 | 1820.0-1825.0 | 1825.0-1830.0,1710-1880,Downlink,95,1
402,2355.0000,2385.0000,NaN,NaN,Inválido,NaN,1

In [ ]:
conjunto_de_canais.Intervalo_Canal.value_counts()

Intervalo_Canal
Downlink    367
Inválido     36
Name: count, dtype: int64

In [ ]:
df_out = pd.merge(df_sub, conjunto_de_canais, how='left', on=['Início_Canal_Down', 'Fim_Canal_Down'])

Total de Agrupamentos Inválidos

In [ ]:
df_out.Intervalo_Canal.value_counts()

Intervalo_Canal
Downlink    141177
Inválido      1402
Name: count, dtype: int64

In [ ]:
df_out.sample(5)

,Num_Ato,Validade_RF,Fistel,Entidade,Número_Estação,Latitude,Longitude,Código_Município,UF,Potência(W),...,Largura_Emissão(kHz),Classe_Emissão,Início_Canal_Down,Fim_Canal_Down,Multiplicidade,Blocos_Downlink,Faixas,Intervalo_Canal,Offset,Total
18362,16992008.0,2023-04-30,50409314250,TIM S A ...,431354324,-27.052833,-49.523194,4206900,SC,60.0,...,5000.0,G7W,2147.50,2152.50,3,2145.0-2150.0 | 2150.0-2155.0,1920-2170,Downlink,190,1434
129144,73852008,2023-11-28,50409428698,TIM S A ...,1011077172,-7.360489,-39.046559,2300101,CE,40.0,...,10000.0,G7W,869.50,879.50,3,869.0-874.0 | 874.0-879.0 | 879.0-884.0,819-894,Downlink,45,334
5542,41662008,2023-04-30,50409146447,TELEFONICA BRASIL S.A.,5139546,-22.415428,-50.578697,3535507,SP,35.0,...,200.0,G7W,890.65,890.85,10,889.0-894.0,819-894,Downlink,45,1044
56522,35332011,2023-04-30,50409889580,CLARO S.A.,684998025,-26.90221,-52.9127,4211405,SC,40.0,...,2500.0,G7W,1870.00,1872.50,3,1870.0-1875.0,1710-1880,Downlink,95,278
109041,73852008,2023-11-28,50409428698,TIM S/A,699269709,-4.100278,-40.428611,2312205,CE,80.000,...,5000.0,G9W,877.50,882.50,3,874.0-879.0 | 879.0-884.0,819-894,Downlink,45,1666

Total de Estações cuja Frequência de Transmissão não pertence a nenhum canal válido

In [ ]:
df_out.loc[df_out.Intervalo_Canal == 'Inválido', 'Multiplicidade'].sum()

49675

In [ ]:
df_bad = df_out.loc[df_out.Intervalo_Canal == 'Inválido'].reset_index(drop=True)

Vamos excluir os registros inválidos do nosso resultado

In [ ]:
df_out = df_out.loc[df_out.Intervalo_Canal != 'Inválido'].reset_index(drop=True)

In [ ]:
df_out.Faixas.str.contains('\|').sum()

467

Para checar que temos, conforme esperado, um offset único para dado conjunto de blocos que o canal está inserido. Em outras palavras, temos que garantir que o Canal, mesmo que ocupe mais de 1 bloco de frequência, ou mesmo mais de uma faixa da canalização. 

Por quê isso? 

Porque iremos utilizar esse offset para determinar a frequência de recepção teórica à partir da frequência de transmissão e para tal não faz sentido ter mais de 1 valor de offset.

In [ ]:
df_out.Offset.str.contains('\|').sum()

0

In [ ]:
df_out['Frequência_Recepção_Teórica'] = df_out.Frequência_Transmissão.astype('float') - df_out.Offset.astype('float')

In [ ]:
df_out.sample(10)

,Num_Ato,Validade_RF,Fistel,Entidade,Número_Estação,Latitude,Longitude,Código_Município,UF,Potência(W),...,Classe_Emissão,Início_Canal_Down,Fim_Canal_Down,Multiplicidade,Blocos_Downlink,Faixas,Intervalo_Canal,Offset,Total,Frequência_Recepção_Teórica
36835,35312011,2023-04-30,50409146366,TELEFÔNICA BRASIL S.A.,682665274,-25.57917,-49.36528,4101804,PR,39.500,...,G7W,1859.9,1860.1,3,1855.0-1860.0 | 1860.0-1865.0,1710-1880,Downlink,95,404,1765.0
82836,59592012,2032-12-22,50409307637,CLARO S.A.,690551711,-5.33864,-49.09152,1504208,PA,60.0,...,G7W,2630.0,2650.0,54,2630.0-2635.0 | 2635.0-2640.0 | 2640.0-2645.0 ...,2500-2690,Downlink,120,1242,2520.0
76755,48412023,2038-04-30,50409146285,TELEFONICA BRASIL S.A.,689665296,-21.71694,-46.38583,3105301,MG,40.0,...,G9W,2157.5,2162.5,2,2155.0-2160.0 | 2160.0-2165.0,1920-2170,Downlink,190,3810,1970.0
102959,16992008.0,2023-04-30,50010613854,TIM S/A,695541218,-22.62889,-47.19861,3512803,SP,61.500,...,G7W,2132.5,2137.5,3,2130.0-2135.0 | 2135.0-2140.0,1920-2170,Downlink,190,2051,1945.0
132480,29272013.0,2023-04-30,50409314250,TIM S A,1013053580,-27.50559444,-52.60624722,4302055,RS,40.0,...,G7W,1825.0,1830.0,3,1825.0-1830.0,1710-1880,Downlink,95,697,1732.5
19740,59592012,2027-10-18,50409889580,CLARO S.A.,441537847,-28.38667,-53.89167,4310207,RS,40.0,...,G7W,2640.0,2660.0,21,2640.0-2645.0 | 2645.0-2650.0 | 2650.0-2655.0 ...,2500-2690,Downlink,120,1166,2530.0
44166,47102015,2031-03-11,50010613854,TIM S/A,684046709,-20.75906,-49.70272,3531407,SP,80,...,G7W,1824.9,1825.1,4,1820.0-1825.0 | 1825.0-1830.0,1710-1880,Downlink,95,1647,1730.0
1067,59072012,2038-04-30,50409146285,TELEFONICA BRASIL S.A.,603368,-18.91611,-47.00583,3148103,MG,80.0,...,G7W,2670.0,2690.0,40,2670.0-2675.0 | 2675.0-2680.0 | 2680.0-2685.0 ...,2500-2690,Downlink,120,2734,2560.0
58771,46662011,2027-08-06,50409105090,CLARO S.A.,686130588,-23.44389,-46.88278,3547304,SP,45.91,...,G9W,891.5,896.5,3,889.0-894.0,819-894,Downlink,45,555,849.0
121179,34672011,2026-06-01,50409307637,CLARO S.A.,1004125795,-7.50865,-63.03621,1301704,AM,60.0,...,G7W,1850.0,1860.0,3,1850.0-1855.0 | 1855.0-1860.0,1710-1880,Downlink,95,1962,1760.0

In [ ]:
df_out.Offset.value_counts()

Offset
95     55102
45     29658
190    26980
55     16303
120    13107
10        27
Name: count, dtype: int64

In [ ]:
(df_out.Multiplicidade == 1).sum()

2510

In [ ]:
df_out.to_parquet(folder / 'dados_smp_processados.parquet.gzip', compression='gzip')

In [ ]:
df_out.columns

Index(['Num_Ato', 'Validade_RF', 'Fistel', 'Entidade', 'Número_Estação',
       'Latitude', 'Longitude', 'Código_Município', 'UF', 'Potência(W)',
       'Cod_TipoAntena', 'Polarização', 'Raio_Antena', 'Ganho_Antena',
       'FC_Antena', 'Ang_MP_Antena', 'Ângulo_Elevação', 'Azimute',
       'Altura_Antena', 'Perdas_Acessorias', 'Tipo_Estação', 'Tecnologia',
       'Frequência_Transmissão', 'Frequência_Recepção', 'Largura_Emissão(kHz)',
       'Classe_Emissão', 'Início_Canal_Down', 'Fim_Canal_Down',
       'Multiplicidade', 'Blocos_Downlink', 'Faixas', 'Intervalo_Canal',
       'Offset', 'Total', 'Frequência_Recepção_Teórica'],
      dtype='object')

In [ ]:
# ibge = pd.read_excel(folder / 'municipios_coordenadas.xlsx', dtype='string')
ibge = pd.read_csv(folder.parent / 'extracao' / 'arquivos' / 'municipios_ibge.csv', dtype='string')

In [ ]:
ibge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   codigo_ibge  5570 non-null   string
 1   nome         5570 non-null   string
 2   latitude     5570 non-null   string
 3   longitude    5570 non-null   string
 4   capital      5570 non-null   string
 5   codigo_uf    5570 non-null   string
dtypes: string(6)
memory usage: 261.2 KB

In [ ]:
ibge.sample(5)

     codigo_ibge                    nome  latitude longitude capital codigo_uf
1151     2604106                 Caruaru  -8.28455  -35.9699       0        26
4756     2514404  São José de Espinharas  -6.83974  -37.3214       0        25
4064     4120804           Quatro Barras  -25.3673  -49.0763       0        41
1995     4109005               Guapirama  -23.5203  -50.0407       0        41
4972     1507805   Senador José Porfírio  -4.31242  -51.5764       0        15

In [ ]:
ibge.columns = ['Código_Município', 'Município', 'Latitude', 'Longitude', 'Capital', 'Código_UF']

In [ ]:
smp = pd.read_parquet(folder / 'dados_smp_processados.parquet.gzip').astype('string')

Os dados que foram agregados por `['UF', 'Código_Município', 'Fistel', 'Frequência_Transmissão', 'Largura_Emissão(kHz)', 'Classe_Emissão']`. A coluna `Multiplicidade` guarda a contagem de estações agrupadas para dado conjunto de valores dessas colunas.

Para os registros que possuem `Multiplicidade=1`, não houve agregação e a estação é única. Para esses a coordenada da estação é mantida. Para todos os demais registros as coordenadas serão substituídas pela coordenada do município. Fazer processamento como imputar uma média das coordenadas não agrega valor "fiscalizatório" porque gera uma coordenada que não existe. A substituição pela coordenada central do município tem o propósito simplesmente de dar a localidade na qual aquele conjunto de estações serve.

In [ ]:
coords_municipio = pd.merge(smp.loc[smp.Multiplicidade != '1', 'Código_Município'], ibge[['Código_Município', 'Latitude', 'Longitude']], 
                            on='Código_Município', 
                            how='left')

In [ ]:
smp.loc[smp.Multiplicidade != '1', ['Latitude', 'Longitude']] = coords_municipio[['Latitude', 'Longitude']].values

In [ ]:
smp['Coords_Valida_IBGE'] = '1'

In [ ]:
smp.loc[smp.Multiplicidade != '1', 'Coords_Valida_IBGE'] = '0'

In [ ]:
smp[['Latitude_IBGE', 'Longitude_IBGE']] = smp[['Latitude', 'Longitude']]

In [ ]:
smp.sample(5)

,Num_Ato,Validade_RF,Fistel,Entidade,Número_Estação,Latitude,Longitude,Código_Município,UF,Potência(W),...,Multiplicidade,Blocos_Downlink,Faixas,Intervalo_Canal,Offset,Total,Frequência_Recepção_Teórica,Coords_Valida_IBGE,Latitude_IBGE,Longitude_IBGE
1024,125002022,2028-11-29,50409314250,TIM S A,565490,-23.2659,-51.0522,4109807,PR,60.0,...,5,1820.0-1825.0 | 1825.0-1830.0,1710-1880,Downlink,95,1647,1730.0,0,-23.2659,-51.0522
140258,13652021,2023-04-30,50409146285,TELEFONICA BRASIL S.A.,1014937393,-6.48529,-37.4488,2513901,PB,40.0,...,3,2125.0-2130.0 | 2130.0-2135.0,1920-2170,Downlink,190,2546,1940.0,0,-6.48529,-37.4488
109934,149592017.0,2032-12-18,50409889580,CLARO S.A.,700009752,-25.8515,-52.5173,4105409,PR,40.0,...,3,1875.0-1880.0,1710-1880,Downlink,95,1872,1785.0,0,-25.8515,-52.5173
85573,34672011,2026-06-01,50409307637,CLARO S.A.,690761295,-4.09412,-63.1441,1301209,AM,60.0,...,3,1850.0-1855.0 | 1855.0-1860.0,1710-1880,Downlink,95,1053,1760.0,0,-4.09412,-63.1441
46207,16952008.0,2032-12-12,50409307637,CLARO S.A.,684357836,-10.4374,-39.3321,2921500,BA,50.0,...,3,2145.0-2150.0 | 2150.0-2155.0,1920-2170,Downlink,190,1434,1960.0,0,-10.4374,-39.3321

In [ ]:
municipio = pd.merge(smp[['Código_Município']], ibge[['Código_Município', 'Município']], 
                            on='Código_Município', 
                            how='left')

In [ ]:
municipio[municipio.Município.isna()]

       Código_Município Município
122060        3530607        <NA>
122061        3530607        <NA>

In [ ]:
# municipio.loc[municipio.Município.isna(), 'Município'] = 'Mogi das Cruzes'

In [ ]:
smp['Status'] = 'L'
smp['Num_Serviço'] = '010'

In [ ]:
smp['Município_IBGE'] = municipio.Município.values

In [ ]:
from extracao.format import merge_on_frequency, _filter_matlab, _format_matlab
from extracao.constants import COLUNAS

In [ ]:
down = smp.rename(columns={'Frequência_Transmissão' : 'Frequência'}).copy()
down = down.drop('Frequência_Recepção_Teórica', axis=1)

In [ ]:
down['Fonte'] = 'MOS'
down['Classe'] = 'FB'

In [ ]:
up = smp.rename(columns={'Frequência_Recepção_Teórica' : 'Frequência'}).copy()
up = up.drop('Frequência_Transmissão', axis=1)

In [ ]:
up['Fonte'] = 'DOC'
up['Classe'] = 'ML'

In [ ]:
smp = pd.concat([down, up], ignore_index=True)

In [ ]:
smp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282354 entries, 0 to 282353
Data columns (total 42 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Num_Ato               282354 non-null  string
 1   Validade_RF           282354 non-null  string
 2   Fistel                282354 non-null  string
 3   Entidade              282354 non-null  string
 4   Número_Estação        282354 non-null  string
 5   Latitude              282350 non-null  string
 6   Longitude             282350 non-null  string
 7   Código_Município      282354 non-null  string
 8   UF                    282354 non-null  string
 9   Potência(W)           282354 non-null  string
 10  Cod_TipoAntena        282354 non-null  string
 11  Polarização           282354 non-null  string
 12  Raio_Antena           109716 non-null  string
 13  Ganho_Antena          282354 non-null  string
 14  FC_Antena             282354 non-null  string
 15  Ang_MP_Antena         282354 non-null  string
 16  Ângulo_Elevação       282354 non-null  string
 17  Azimute               282354 non-null  string
 18  Altura_Antena         282354 non-null  string
 19  Perdas_Acessorias     282354 non-null  string
 20  Tipo_Estação          282354 non-null  string
 21  Tecnologia            282354 non-null  string
 22  Frequência            282354 non-null  string
 23  Frequência_Recepção   282352 non-null  string
 24  Largura_Emissão(kHz)  282354 non-null  string
 25  Classe_Emissão        282354 non-null  string
 26  Início_Canal_Down     282354 non-null  string
 27  Fim_Canal_Down        282354 non-null  string
 28  Multiplicidade        282354 non-null  string
 29  Blocos_Downlink       282354 non-null  string
 30  Faixas                282354 non-null  string
 31  Intervalo_Canal       282354 non-null  string
 32  Offset                282354 non-null  string
 33  Total                 282354 non-null  string
 34  Coords_Valida_IBGE    282354 non-null  object
 35  Latitude_IBGE         282350 non-null  string
 36  Longitude_IBGE        282350 non-null  string
 37  Status                282354 non-null  object
 38  Num_Serviço           282354 non-null  object
 39  Município_IBGE        282354 non-null  string
 40  Fonte                 282354 non-null  object
 41  Classe                282354 non-null  object
dtypes: object(5), string(37)
memory usage: 90.5+ MB

In [ ]:
df = _filter_matlab(smp)

In [ ]:
df = _format_matlab(df)

In [ ]:
df[df.Description.str.contains('*', regex=False)]

,Id,Frequency,Latitude,Longitude,Description,Service,Station,Class,BW
0,#1,454.5,-15.110000,-40.068401,"[DOC] L, ML, Claro S.A. (50409307637, 10026280...",10,1002628048,G7W,5000.0
1,#2,454.5,-15.022500,-42.372700,"[DOC] L, ML, Claro S.A. (50409307637, 10022640...",10,1002264003,G7W,5000.0
2,#3,454.5,-14.767800,-42.649799,"[DOC] L, ML, Claro S.A. (50409307637, 10021314...",10,1002131429,G7W,5000.0
3,#4,454.5,-14.571000,-42.943401,"[DOC] L, ML, Claro S.A. (50409307637, 10020029...",10,1002002904,G7W,5000.0
4,#5,454.5,-14.384700,-41.884201,"[DOC] L, ML, Claro S.A. (50409307637, 10022545...",10,1002254539,G7W,5000.0
...,...,...,...,...,...,...,...,...,...
282349,#282350,2690.0,0.034934,-51.069401,"[MOS] L, FB, Telefônica Brasil S.A. (504091462...",10,690246692,G7W,200.0
282350,#282351,2690.0,0.034934,-51.069401,"[MOS] L, FB, Telefônica Brasil S.A. (504091462...",10,695978241,G7W,5000.0
282351,#282352,2690.0,0.939956,-60.438900,"[MOS] L, FB, Telefônica Brasil S.A. (504091462...",10,691058440,G7W,20000.0
282352,#282353,2690.0,1.827660,-61.130402,"[MOS] L, FB, Telefonica Brasil S.A. (504091462...",10,687270995,G7W,20000.0
282353,#282354,2690.0,2.823840,-60.675301,"[MOS] L, FB, Telefônica Brasil S.A. (504091462...",10,442820496,G7W,20000.0

In [ ]:
df.to_parquet(folder / 'smp_processado.parquet.gzip', compression='gzip')