## Canalização

| N_Bloco   |   Uplink_Inicial |   Uplink_Final |   Downlink_Inicial |   Downlink_Final | Faixa     |
|:----------|-----------------:|---------------:|-------------------:|-----------------:|:----------|
| 1         |            451   |          451.1 |              461   |            461.1 | 451-468   |
| 2         |            451.1 |          451.2 |              461.1 |            461.2 | 451-468   |
| 3         |            451.2 |          451.3 |              461.2 |            461.3 | 451-468   |
| 4         |            451.3 |          451.4 |              461.3 |            461.4 | 451-468   |
| 5         |            451.4 |          451.5 |              461.4 |            461.5 | 451-468   |
| 6         |            451.5 |          451.6 |              461.5 |            461.6 | 451-468   |
| 7         |            451.6 |          451.7 |              461.6 |            461.7 | 451-468   |
| 8         |            451.7 |          451.8 |              461.7 |            461.8 | 451-468   |
| 9         |            451.8 |          451.9 |              461.8 |            461.9 | 451-468   |
| 10        |            451.9 |          452   |              461.9 |            462   | 451-468   |
| 11        |            452   |          452.1 |              462   |            462.1 | 451-468   |
| 12        |            452.1 |          452.2 |              462.1 |            462.2 | 451-468   |
| 13        |            452.2 |          452.3 |              462.2 |            462.3 | 451-468   |
| 14        |            452.3 |          452.4 |              462.3 |            462.4 | 451-468   |
| 15        |            452.4 |          452.5 |              462.4 |            462.5 | 451-468   |
| 16        |            452.5 |          452.6 |              462.5 |            462.6 | 451-468   |
| 17        |            452.6 |          452.7 |              462.6 |            462.7 | 451-468   |
| 18        |            452.7 |          452.8 |              462.7 |            462.8 | 451-468   |
| 19        |            452.8 |          452.9 |              462.8 |            462.9 | 451-468   |
| 20        |            452.9 |          453   |              462.9 |            463   | 451-468   |
| 21        |            453   |          453.1 |              463   |            463.1 | 451-468   |
| 22        |            453.1 |          453.2 |              463.1 |            463.2 | 451-468   |
| 23        |            453.2 |          453.3 |              463.2 |            463.3 | 451-468   |
| 24        |            453.3 |          453.4 |              463.3 |            463.4 | 451-468   |
| 25        |            453.4 |          453.5 |              463.4 |            463.5 | 451-468   |
| 26        |            453.5 |          453.6 |              463.5 |            463.6 | 451-468   |
| 27        |            453.6 |          453.7 |              463.6 |            463.7 | 451-468   |
| 28        |            453.7 |          453.8 |              463.7 |            463.8 | 451-468   |
| 29        |            453.8 |          453.9 |              463.8 |            463.9 | 451-468   |
| 30        |            453.9 |          454   |              463.9 |            464   | 451-468   |
| 31        |            454   |          454.1 |              464   |            464.1 | 451-468   |
| 32        |            454.1 |          454.2 |              464.1 |            464.2 | 451-468   |
| 33        |            454.2 |          454.3 |              464.2 |            464.3 | 451-468   |
| 34        |            454.3 |          454.4 |              464.3 |            464.4 | 451-468   |
| 35        |            454.4 |          454.5 |              464.4 |            464.5 | 451-468   |
| 36        |            454.5 |          454.6 |              464.5 |            464.6 | 451-468   |
| 37        |            454.6 |          454.7 |              464.6 |            464.7 | 451-468   |
| 38        |            454.7 |          454.8 |              464.7 |            464.8 | 451-468   |
| 39        |            454.8 |          454.9 |              464.8 |            464.9 | 451-468   |
| 40        |            454.9 |          455   |              464.9 |            465   | 451-468   |
| 41        |            455   |          455.1 |              465   |            465.1 | 451-468   |
| 42        |            455.1 |          455.2 |              465.1 |            465.2 | 451-468   |
| 43        |            455.2 |          455.3 |              465.2 |            465.3 | 451-468   |
| 44        |            455.3 |          455.4 |              465.3 |            465.4 | 451-468   |
| 45        |            455.4 |          455.5 |              465.4 |            465.5 | 451-468   |
| 46        |            455.5 |          455.6 |              465.5 |            465.6 | 451-468   |
| 47        |            455.6 |          455.7 |              465.6 |            465.7 | 451-468   |
| 48        |            455.7 |          455.8 |              465.7 |            465.8 | 451-468   |
| 49        |            455.8 |          455.9 |              465.8 |            465.9 | 451-468   |
| 50        |            455.9 |          456   |              465.9 |            466   | 451-468   |
| 51        |            456   |          456.1 |              466   |            466.1 | 451-468   |
| 52        |            456.1 |          456.2 |              466.1 |            466.2 | 451-468   |
| 53        |            456.2 |          456.3 |              466.2 |            466.3 | 451-468   |
| 54        |            456.3 |          456.4 |              466.3 |            466.4 | 451-468   |
| 55        |            456.4 |          456.5 |              466.4 |            466.5 | 451-468   |
| 56        |            456.5 |          456.6 |              466.5 |            466.6 | 451-468   |
| 57        |            456.6 |          456.7 |              466.6 |            466.7 | 451-468   |
| 58        |            456.7 |          456.8 |              466.7 |            466.8 | 451-468   |
| 59        |            456.8 |          456.9 |              466.8 |            466.9 | 451-468   |
| 60        |            456.9 |          457   |              466.9 |            467   | 451-468   |
| 61        |            457   |          457.1 |              467   |            467.1 | 451-468   |
| 62        |            457.1 |          457.2 |              467.1 |            467.2 | 451-468   |
| 63        |            457.2 |          457.3 |              467.2 |            467.3 | 451-468   |
| 64        |            457.3 |          457.4 |              467.3 |            467.4 | 451-468   |
| 65        |            457.4 |          457.5 |              467.4 |            467.5 | 451-468   |
| 66        |            457.5 |          457.6 |              467.5 |            467.6 | 451-468   |
| 67        |            457.6 |          457.7 |              467.6 |            467.7 | 451-468   |
| 68        |            457.7 |          457.8 |              467.7 |            467.8 | 451-468   |
| 69        |            457.8 |          457.9 |              467.8 |            467.9 | 451-468   |
| 70        |            457.9 |          458   |              467.9 |            468   | 451-468   |
| 1         |            703   |          708   |              758   |            763   | 703-803   |
| 2         |            708   |          713   |              763   |            768   | 703-803   |
| 3         |            713   |          718   |              768   |            773   | 703-803   |
| 4         |            718   |          723   |              773   |            778   | 703-803   |
| 5         |            723   |          728   |              778   |            783   | 703-803   |
| 6         |            728   |          733   |              783   |            788   | 703-803   |
| 7         |            733   |          738   |              788   |            793   | 703-803   |
| 8         |            738   |          743   |              793   |            798   | 703-803   |
| 9         |            743   |          748   |              798   |            803   | 703-803   |
| 1         |            819   |          824   |              864   |            869   | 819-894   |
| 2         |            824   |          829   |              869   |            874   | 819-894   |
| 3         |            829   |          834   |              874   |            879   | 819-894   |
| 4         |            834   |          839   |              879   |            884   | 819-894   |
| 5         |            839   |          844   |              884   |            889   | 819-894   |
| 6         |            844   |          849   |              889   |            894   | 819-894   |
| 1         |            898.5 |          901   |              943.5 |            946   | 898.5-960 |
| 2         |            905   |          907.5 |              950   |            952.5 | 898.5-960 |
| 3         |            907.5 |          910   |              952.5 |            955   | 898.5-960 |
| 4         |            910   |          912.5 |              955   |            957.5 | 898.5-960 |
| 5         |            912.5 |          915   |              957.5 |            960   | 898.5-960 |
| 1         |           1710   |         1715   |             1805   |           1810   | 1710-1880 |
| 2         |           1715   |         1720   |             1810   |           1815   | 1710-1880 |
| 3         |           1720   |         1725   |             1815   |           1820   | 1710-1880 |
| 4         |           1725   |         1730   |             1820   |           1825   | 1710-1880 |
| 5         |           1730   |         1735   |             1825   |           1830   | 1710-1880 |
| 6         |           1735   |         1740   |             1830   |           1835   | 1710-1880 |
| 7         |           1740   |         1745   |             1835   |           1840   | 1710-1880 |
| 8         |           1745   |         1750   |             1840   |           1845   | 1710-1880 |
| 9         |           1750   |         1755   |             1845   |           1850   | 1710-1880 |
| 10        |           1755   |         1760   |             1850   |           1855   | 1710-1880 |
| 11        |           1760   |         1765   |             1855   |           1860   | 1710-1880 |
| 12        |           1765   |         1770   |             1860   |           1865   | 1710-1880 |
| 13        |           1770   |         1775   |             1865   |           1870   | 1710-1880 |
| 14        |           1775   |         1780   |             1870   |           1875   | 1710-1880 |
| 15        |           1780   |         1785   |             1875   |           1880   | 1710-1880 |
| 1         |           1920   |         1925   |             2110   |           2115   | 1920-2170 |
| 2         |           1925   |         1930   |             2115   |           2120   | 1920-2170 |
| 3         |           1930   |         1935   |             2120   |           2125   | 1920-2170 |
| 4         |           1935   |         1940   |             2125   |           2130   | 1920-2170 |
| 5         |           1940   |         1945   |             2130   |           2135   | 1920-2170 |
| 6         |           1945   |         1950   |             2135   |           2140   | 1920-2170 |
| 7         |           1950   |         1955   |             2140   |           2145   | 1920-2170 |
| 8         |           1955   |         1960   |             2145   |           2150   | 1920-2170 |
| 9         |           1960   |         1965   |             2150   |           2155   | 1920-2170 |
| 10        |           1965   |         1970   |             2155   |           2160   | 1920-2170 |
| 11        |           1970   |         1975   |             2160   |           2165   | 1920-2170 |
| 12        |           1975   |         1980   |             2165   |           2170   | 1920-2170 |
| 1         |           1980   |         1985   |             2170   |           2175   | 1980-2200 |
| 2         |           1985   |         1990   |             2175   |           2180   | 1980-2200 |
| 3         |           1990   |         1995   |             2180   |           2185   | 1980-2200 |
| 4         |           1995   |         2000   |             2185   |           2190   | 1980-2200 |
| 5         |           2000   |         2005   |             2190   |           2195   | 1980-2200 |
| 6         |           2005   |         2010   |             2195   |           2200   | 1980-2200 |
| 1         |           2500   |         2505   |             2620   |           2625   | 2500-2690 |
| 2         |           2505   |         2510   |             2625   |           2630   | 2500-2690 |
| 3         |           2510   |         2515   |             2630   |           2635   | 2500-2690 |
| 4         |           2515   |         2520   |             2635   |           2640   | 2500-2690 |
| 5         |           2520   |         2525   |             2640   |           2645   | 2500-2690 |
| 6         |           2525   |         2530   |             2645   |           2650   | 2500-2690 |
| 7         |           2530   |         2535   |             2650   |           2655   | 2500-2690 |
| 8         |           2535   |         2540   |             2655   |           2660   | 2500-2690 |
| 9         |           2540   |         2545   |             2660   |           2665   | 2500-2690 |
| 10        |           2545   |         2550   |             2665   |           2670   | 2500-2690 |
| 11        |           2550   |         2555   |             2670   |           2675   | 2500-2690 |
| 12        |           2555   |         2560   |             2675   |           2680   | 2500-2690 |
| 13        |           2560   |         2565   |             2680   |           2685   | 2500-2690 |
| 14        |           2565   |         2570   |             2685   |           2690   | 2500-2690 |
| 15        |           2570   |         2575   |             2570   |           2575   | 2500-2690 |
| 16        |           2575   |         2580   |             2575   |           2580   | 2500-2690 |
| 17        |           2580   |         2585   |             2580   |           2585   | 2500-2690 |
| 18        |           2585   |         2590   |             2585   |           2590   | 2500-2690 |
| 19        |           2590   |         2595   |             2590   |           2595   | 2500-2690 |
| 20        |           2595   |         2600   |             2595   |           2600   | 2500-2690 |
| 21        |           2600   |         2605   |             2600   |           2605   | 2500-2690 |
| 22        |           2605   |         2610   |             2605   |           2610   | 2500-2690 |
| 23        |           2610   |         2615   |             2610   |           2615   | 2500-2690 |
| 24        |           2615   |         2620   |             2615   |           2620   | 2500-2690 |
| C-3       |            nan   |          nan   |             2570   |           2576   | 2570-2618 |
| C-4       |            nan   |          nan   |             2582   |           2588   | 2570-2618 |
| D-3       |            nan   |          nan   |             2576   |           2582   | 2570-2618 |
| D-4       |            nan   |          nan   |             2588   |           2594   | 2570-2618 |
| E-1       |            nan   |          nan   |             2594   |           2600   | 2570-2618 |
| E-2       |            nan   |          nan   |             2606   |           2612   | 2570-2618 |
| F-1       |            nan   |          nan   |             2600   |           2606   | 2570-2618 |
| F-2       |            nan   |          nan   |             2612   |           2618   | 2570-2618 |

## Processamento

In [ ]:
import sys
from pathlib import Path
import pandas as pd 
import numpy as np

In [ ]:
sys.path.insert(0, str(Path().cwd().parent))
%load_ext autoreload
%autoreload 2

In [ ]:
from extracao.format import parse_bw
from extracao.updates import split_designacao

In [ ]:
COLS_SMP = {
    "NumAto": "Num_Ato",
    "NumFistel": "Fistel",
    "NomeEntidade": "Entidade",
    "SiglaUf": "UF",
    "NumEstacao": "Número_Estação",
    "CodMunicipio": "Código_Município",
    "DataValidade": "Validade_RF",
    "FreqInicialMHz": "Frequência_Inicial",
    "FreqCentralMHz": "Frequência_Central",
    "FreqTxMHz": "Frequência_Transmissão",
    "FreqRxMHz": "Frequência_Recepção",
    "FreqFinalMHz": "Frequência_Final",
    "formId": "Tipo_Estação",
    "Tecnologia": "Tecnologia",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "DesignacaoEmissao": "Designação_Emissão",
    "PotenciaTransmissorWatts": "Potência(W)",
    "CodTipoAntena": "Cod_TipoAntena",
    "Polarizacao": "Polarização",
    "RaioAntena": "Raio_Antena",
    "GanhoAntena": "Ganho_Antena",
    "FrenteCostaAntena": "FC_Antena",
    "AnguloMeiaPotenciaAntena": "Ang_MP_Antena",
    "AnguloElevacao": "Ângulo_Elevação",
    "Azimute": "Azimute",
    "AlturaAntena": "Altura_Antena",
    "PerdasAcessorias": "Perdas_Acessorias",
}

DTYPE_SMP = {
    "NumAto": "category",
    "NumFistel": "category",
    "NomeEntidade": "category",
    "SiglaUf": "category",
    "NumEstacao": "string",
    "CodMunicipio": "category",
    "DataValidade": "category",
    "FreqInicialMHz": "category",
    "FreqCentralMHz": "category",
    "FreqFinalMHz": "category",
    "FreqTxMHz": "category",
    "FreqRxMHz": "category",
    "formId": "category",
    "Tecnologia": "category",
    "Latitude": "float",
    "Longitude": "float",
    "DesignacaoEmissao": "category",
    "PotenciaTransmissorWatts": "float",
    "CodTipoAntena": "category",
    "Polarizacao": "category",
    "RaioAntena": "float",
    "GanhoAntena": "float",
    "FrenteCostaAntena": "float",
    "AnguloMeiaPotenciaAntena": "float",
    "AnguloElevacao": "float",
    "Azimute": "float",
    "AlturaAntena": "float",
    "PerdasAcessorias": "float",
}

In [ ]:
folder = Path.cwd().parent / 'dados'

In [ ]:
df = pd.read_parquet(folder / 'smp_formated.parquet.gzip')

In [ ]:
df = df.rename(columns=COLS_SMP)

In [ ]:
df.sample(5)

,Num_Ato,Validade_RF,Fistel,Entidade,Número_Estação,Latitude,Longitude,Frequência_Inicial,Frequência_Final,Frequência_Central,...,FC_Antena,Ang_MP_Antena,Ângulo_Elevação,Azimute,Altura_Antena,Perdas_Acessorias,Tipo_Estação,Tecnologia,Frequência_Transmissão,Frequência_Recepção
1578194,69272020,2023-04-30,50409314250,TIM S A,683574752,-15.640778,-55.973361,<NA>,<NA>,<NA>,...,25.0,65.0,0.0,320.0,65.0,0.0,base,WCDMA,2150.0,1960.0
674128,1432016.0,2027-10-18,50409314250,TIM S/A,1002916531,-26.89361,-49.09778,2660.0,2670.0,2665,...,22.0,66.00,5.90,35.0,41.0,,base,LTE,2670.0,2660.0
1404334,47102015,2029-12-08,50010613854,TIM S A,1009551849,-23.580389,-46.68625,<NA>,<NA>,<NA>,...,25.0,65.0,-1.0,15.0,36.4,0.0,base,LTE,1832.5,1737.5
1352219,12842020,2029-12-08,50010613854,TIM S A,1001836640,-23.530889,-46.618167,<NA>,<NA>,936.25,...,25.0,74.0,-8.0,235.0,44.0,0.0,base,WCDMA,958.75,913.75
156923,48372023,2028-03-31,50409105090,CLARO S.A.,641251556,-23.35358,-47.51113,<NA>,<NA>,2117.5,...,20.0,65.0,1.0,290.0,56.0,0.0,base,WCDMA,2117.5,1927.5

In [ ]:
df = split_designacao(df)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1950054 entries, 0 to 1949980
Data columns (total 29 columns):
 #   Column                  Dtype
---  ------                  -----
 0   Num_Ato                 string
 1   Validade_RF             string
 2   Fistel                  string
 3   Entidade                string
 4   Número_Estação          string
 5   Latitude                string
 6   Longitude               string
 7   Frequência_Inicial      string
 8   Frequência_Final        string
 9   Frequência_Central      string
 10  Código_Município        string
 11  UF                      string
 12  Potência(W)             string
 13  Cod_TipoAntena          string
 14  Polarização             string
 15  Raio_Antena             string
 16  Ganho_Antena            string
 17  FC_Antena               string
 18  Ang_MP_Antena           string
 19  Ângulo_Elevação         string
 20  Azimute                 string
 21  Altura_Antena           string
 22  Perdas_Acessorias       string
 23  Tipo_Estação            string
 24  Tecnologia              string
 25  Frequência_Transmissão  string
 26  Frequência_Recepção     string
 27  Largura_Emissão(kHz)    string
 28  Classe_Emissão          string
dtypes: string(29)
memory usage: 446.3 MB

A Frequência Central possui muitas lacunas nos dados, a frequência de transmissão será o dado utilizado.

In [ ]:
df[df.Frequência_Central.isna()].shape

(595832, 29)

In [ ]:
df[df.Frequência_Central == df.Frequência_Transmissão].shape

(309355, 29)

In [ ]:
df[df.Frequência_Final == df.Frequência_Transmissão].shape

(595119, 29)

In [ ]:
df[df.Frequência_Inicial == df.Frequência_Transmissão].shape

(24, 29)

Criar canais de Transmissão - Downlink

In [ ]:
subset = ['Código_Município', 'Fistel', 'Frequência_Transmissão', 'Largura_Emissão(kHz)', 'Classe_Emissão', 'Tecnologia']

Como vamos agrupar diversas estações baseadas em um subconjunto de colunas, vamos ordenar os dados de forma crescente pelo número da estação. Assim ao agruparmos diversos registros num só, o número da estação desse agrupamento será a estação licenciada mais antiga do grupo, em outras palavras, será mantido o número da estação menor por conta do ordenamento.

In [ ]:
df['Número_Estação'] = df['Número_Estação'].astype(int) 
df = df.sort_values('Número_Estação', ignore_index=True)
df = df.astype('string')

É preciso eliminar dados vazios em qualquer das colunas que serão agrupadas, do contrário há um desalinhamento ao tentar juntar a contagem dos dados agregados.

In [ ]:
df[subset].isna().sum()

Código_Município            0
Fistel                      0
Frequência_Transmissão    215
Largura_Emissão(kHz)       50
Classe_Emissão             50
Tecnologia                  0
dtype: int64

In [ ]:
input_freq = (df.Frequência_Transmissão.isna()) & (df.Frequência_Central.notna())
df.loc[input_freq, 'Frequência_Transmissão'] = df.loc[input_freq, 'Frequência_Central']

In [ ]:
df[subset].isna().sum()

Código_Município           0
Fistel                     0
Frequência_Transmissão     0
Largura_Emissão(kHz)      50
Classe_Emissão            50
Tecnologia                 0
dtype: int64

In [ ]:
input_largura = (df['Largura_Emissão(kHz)'].isna()) & (df['Frequência_Inicial'].notna()) & (df['Frequência_Final'].notna())
df[input_largura]

Empty DataFrame
Columns: [Num_Ato, Validade_RF, Fistel, Entidade, Número_Estação, Latitude, Longitude, Frequência_Inicial, Frequência_Final, Frequência_Central, Código_Município, UF, Potência(W), Cod_TipoAntena, Polarização, Raio_Antena, Ganho_Antena, FC_Antena, Ang_MP_Antena, Ângulo_Elevação, Azimute, Altura_Antena, Perdas_Acessorias, Tipo_Estação, Tecnologia, Frequência_Transmissão, Frequência_Recepção, Largura_Emissão(kHz), Classe_Emissão]
Index: []

[0 rows x 29 columns]

In [ ]:
df['Largura_Emissão(kHz)'].fillna('0', inplace=True)
df['Classe_Emissão'].fillna('NI', inplace=True)

In [ ]:
df[subset].isna().sum()

Código_Município          0
Fistel                    0
Frequência_Transmissão    0
Largura_Emissão(kHz)      0
Classe_Emissão            0
Tecnologia                0
dtype: int64

Eliminar colunas que não serão utilizadas

In [ ]:
df.drop(['Frequência_Inicial', 'Frequência_Central', 'Frequência_Final'], axis=1, inplace=True)

In [ ]:
df.dropna(subset=subset, axis=0, inplace=True)

In [ ]:
df_sub = df[~df.duplicated(subset=subset, keep="first")].reset_index(drop=True)

In [ ]:
df_sub['Multiplicidade'] = df.groupby(subset, sort=False).size().values

In [ ]:
bw = df_sub['Largura_Emissão(kHz)'].astype('float') / 2000 # Unidade em kHz
df_sub['Início_Canal_Down'] = df_sub.Frequência_Transmissão.astype(float) - bw 
df_sub['Fim_Canal_Down'] = df_sub.Frequência_Transmissão.astype(float) + bw

In [ ]:
df_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147555 entries, 0 to 147554
Data columns (total 29 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Num_Ato                 147555 non-null  string
 1   Validade_RF             147555 non-null  string
 2   Fistel                  147555 non-null  string
 3   Entidade                147555 non-null  string
 4   Número_Estação          147555 non-null  string
 5   Latitude                147555 non-null  string
 6   Longitude               147555 non-null  string
 7   Código_Município        147555 non-null  string
 8   UF                      147555 non-null  string
 9   Potência(W)             147555 non-null  string
 10  Cod_TipoAntena          147555 non-null  string
 11  Polarização             147555 non-null  string
 12  Raio_Antena             55267 non-null   string
 13  Ganho_Antena            147555 non-null  string
 14  FC_Antena               147555 non-null  string
 15  Ang_MP_Antena           147555 non-null  string
 16  Ângulo_Elevação         147555 non-null  string
 17  Azimute                 147555 non-null  string
 18  Altura_Antena           147555 non-null  string
 19  Perdas_Acessorias       147555 non-null  string
 20  Tipo_Estação            147555 non-null  string
 21  Tecnologia              147555 non-null  string
 22  Frequência_Transmissão  147555 non-null  string
 23  Frequência_Recepção     147528 non-null  string
 24  Largura_Emissão(kHz)    147555 non-null  string
 25  Classe_Emissão          147555 non-null  string
 26  Multiplicidade          147555 non-null  int64
 27  Início_Canal_Down       147555 non-null  float64
 28  Fim_Canal_Down          147555 non-null  float64
dtypes: float64(2), int64(1), string(26)
memory usage: 32.6 MB

Lendo e formatando o arquivo de canais do serviço SMP, construído à partir da  [Resolução nº 757, de 08 de novembro de 2022](https://informacoes.anatel.gov.br/legislacao/resolucoes/2022/1760-resolucao-757)

In [ ]:
canais = pd.read_excel(folder / 'canalização_smp.xlsx', dtype = 'string')
canais

,N_Bloco,Uplink_Inicial,Uplink_Final,Downlink_Inicial,Downlink_Final,Largura_Bloco(MHz),Offset,Faixa,Tecnologia
0,1,451,451.1,461,461.1,0.10000000000002274,10,451-468,UHF
1,2,451.1,451.2,461.1,461.2,0.0999999999999659,10,451-468,UHF
2,3,451.2,451.3,461.2,461.3,0.10000000000002274,10,451-468,UHF
3,4,451.3,451.4,461.3,461.4,0.0999999999999659,10,451-468,UHF
4,5,451.4,451.5,461.4,461.5,0.10000000000002274,10,451-468,UHF
...,...,...,...,...,...,...,...,...,...
212,46,3750,3760,3750,3760,10,0,3750-3760,5G NR
213,47,3760,3770,3760,3770,10,0,3760-3770,5G NR
214,48,3770,3780,3770,3780,10,0,3770-3780,5G NR
215,49,3780,3790,3780,3790,10,0,3780-3790,5G NR
216,50,3790,3800,3790,3800,10,0,3790-3800,5G NR

In [ ]:
canais.to_csv(Path.cwd().parent / 'extracao' / 'canalizacao_smp.csv', index=False)

In [ ]:
canais[['Downlink_Inicial', 'Downlink_Final']] = canais[['Downlink_Inicial', 'Downlink_Final']].astype(float)
canais[['Uplink_Inicial', 'Uplink_Final']] = canais[['Uplink_Inicial', 'Uplink_Final']].astype(float)
canais = canais.sort_values(['Downlink_Inicial'], ignore_index=True)
canais['N_Bloco'] = canais['N_Bloco'].str.strip()
canais['Faixa'] = canais['Faixa'].str.strip()

In [ ]:
df_sub[['Início_Canal_Down', 'Fim_Canal_Down']] = df_sub[['Início_Canal_Down', 'Fim_Canal_Down']].astype(float)

In [ ]:
conjunto_de_canais = df_sub.groupby(['Início_Canal_Down', 'Fim_Canal_Down']).size().to_frame('Total').reset_index()
conjunto_de_canais.sort_values('Total', ascending=False, inplace=True, ignore_index=True)
conjunto_de_canais

     Início_Canal_Down  Fim_Canal_Down  Total
0              872.000         877.000   4988
1             2157.500        2162.500   4778
2              783.000         793.000   4628
3             2137.500        2142.500   3758
4              773.000         783.000   3705
..                 ...             ...    ...
395           2665.000        2665.000      1
396           2144.900        2145.100      1
397           1817.500        1827.500      1
398           2665.755        2674.245      1
399           1871.250        1878.750      1

[400 rows x 3 columns]

In [ ]:
from tqdm.auto import tqdm
conjunto_de_canais['Intervalo_Canal'] = 'Inválido'
for row in tqdm(conjunto_de_canais.itertuples()):
    interval = canais[(row.Início_Canal_Down < canais['Downlink_Final']) & (row.Fim_Canal_Down > canais['Downlink_Inicial'])]
    faixa = 'Downlink'
    if interval.empty:
        interval = canais[(row.Início_Canal_Down < canais['Uplink_Final']) & (row.Fim_Canal_Down > canais['Uplink_Inicial'])]
        faixa = 'Uplink'
    else:
        down = ' | '.join(interval[['Downlink_Inicial', 'Downlink_Final']].apply(lambda x: f'{x[0]}-{x[1]}', axis=1))
        faixas = ' | '.join(interval.Faixa.unique())
        offset = ' | '.join(interval.Offset.unique())
        conjunto_de_canais.loc[row.Index, ['Blocos_Downlink', 'Faixas', 'Intervalo_Canal', 'Offset']] = down, faixas, faixa, offset

0it [00:00, ?it/s]

In [ ]:
# conjunto_de_canais = conjunto_de_canais[['Início_Canal_Down', 'Fim_Canal_Down', 'Blocos_Downlink', 'Faixas', 'Intervalo_Canal', 'Offset']]
conjunto_de_canais.to_excel(folder / 'canais2canalização.xlsx', index=False)

In [ ]:
conjunto_de_canais

,Início_Canal_Down,Fim_Canal_Down,Total,Intervalo_Canal,Blocos_Downlink,Faixas,Offset
0,872.000,877.000,4988,Downlink,869.0-874.0 | 874.0-879.0,819-894,45
1,2157.500,2162.500,4778,Downlink,2155.0-2160.0 | 2160.0-2165.0,1920-2170,190
2,783.000,793.000,4628,Downlink,783.0-788.0 | 788.0-793.0,703-803,55
3,2137.500,2142.500,3758,Downlink,2135.0-2140.0 | 2140.0-2145.0,1920-2170,190
4,773.000,783.000,3705,Downlink,773.0-778.0 | 778.0-783.0,703-803,55
...,...,...,...,...,...,...,...
395,2665.000,2665.000,1,Inválido,NaN,NaN,NaN
396,2144.900,2145.100,1,Downlink,2140.0-2145.0 | 2145.0-2150.0,1920-2170,190
397,1817.500,1827.500,1,Downlink,1815.0-1820.0 | 1820.0-1825.0 | 1825.0-1830.0,1710-1880,95
398,2665.755,2674.245,1,Downlink,2665.0-2670.0 | 2670.0-2675.0,2500-2690,120
399,1871.250,1878.750,1,Downlink,1870.0-1875.0 | 1875.0-1880.0,1710-1880,95

In [ ]:
conjunto_de_canais[conjunto_de_canais.Intervalo_Canal == 'Inválido']

,Início_Canal_Down,Fim_Canal_Down,Total,Intervalo_Canal,Blocos_Downlink,Faixas,Offset
133,827.0,832.0,228,Inválido,NaN,NaN,NaN
185,1727.5,1732.5,55,Inválido,NaN,NaN,NaN
203,2550.0,2570.0,36,Inválido,NaN,NaN,NaN
214,824.0,835.0,32,Inválido,NaN,NaN,NaN
257,2542.5,2547.5,12,Inválido,NaN,NaN,NaN
275,1727.5,1730.0,7,Inválido,NaN,NaN,NaN
277,1725.0,1735.0,7,Inválido,NaN,NaN,NaN
278,1725.0,1727.5,7,Inválido,NaN,NaN,NaN
287,2640.0,2640.0,5,Inválido,NaN,NaN,NaN
304,824.5,834.5,4,Inválido,NaN,NaN,NaN
325,25350.0,25450.0,2,Inválido,NaN,NaN,NaN
329,25550.0,25650.0,2,Inválido,NaN,NaN,NaN
381,2655.0,2655.0,1,Inválido,NaN,NaN,NaN
385,1775.0,1777.5,1,Inválido,NaN,NaN,NaN
386,1777.5,1780.0,1,Inválido,NaN,NaN,NaN
389,1780.0,1782.5,1,Inválido,NaN,NaN,NaN
390,1782.5,1785.0,1,Inválido,NaN,NaN,NaN
395,2665.0,2665.0,1,Inválido,NaN,NaN,NaN

In [ ]:
conjunto_de_canais[conjunto_de_canais.Intervalo_Canal == 'Inválido'].sort_values('Início_Canal_Down').to_excel(folder / 'canais_nao_validados.xlsx', index=False)

In [ ]:
conjunto_de_canais.Intervalo_Canal.value_counts()

Intervalo_Canal
Downlink    382
Inválido     18
Name: count, dtype: int64

In [ ]:
conjunto_de_canais = conjunto_de_canais[['Início_Canal_Down', 'Fim_Canal_Down', 'Blocos_Downlink', 'Faixas', 'Intervalo_Canal', 'Offset']]

smp = pd.merge(df_sub, conjunto_de_canais, how='left', on=['Início_Canal_Down', 'Fim_Canal_Down'])

Total de Agrupamentos Inválidos

In [ ]:
smp.Intervalo_Canal.value_counts()

Intervalo_Canal
Downlink    147152
Inválido       403
Name: count, dtype: int64

Total de Estações cuja Frequência de Transmissão não pertence a nenhum canal válido

In [ ]:
smp.loc[smp.Intervalo_Canal == 'Inválido', 'Multiplicidade'].sum()

1653

In [ ]:
df_bad = smp.loc[smp.Intervalo_Canal == 'Inválido'].reset_index(drop=True)

In [ ]:
df_bad.to_excel(folder / 'registros_excluidos_canais_invalidos.xlsx', index=False)

Apesar de não validados, esses registros não serão excluídos.

In [ ]:
# smp = smp.loc[smp.Intervalo_Canal != 'Inválido'].reset_index(drop=True)

Para checar que temos, conforme esperado, um offset único para dado conjunto de blocos que o canal está inserido. Em outras palavras, temos que garantir que o Canal, mesmo que ocupe mais de 1 bloco de frequência, ou mesmo mais de uma faixa da canalização. 

Por quê isso? 

Porque iremos utilizar esse offset para determinar a frequência de recepção teórica à partir da frequência de transmissão e para tal não faz sentido ter mais de 1 valor de offset.

In [ ]:
smp.Offset.str.contains('\|').sum()

0

In [ ]:
smp.Offset.value_counts()

Offset
95     55318
190    30331
45     30238
55     16792
120    13358
0       1088
10        27
Name: count, dtype: int64

In [ ]:
smp['Offset'] = pd.to_numeric(smp.Offset, errors='coerce')

In [ ]:
(smp.Offset.isna() == (smp.Intervalo_Canal == 'Inválido')).all()

True

In [ ]:
f = (smp.Intervalo_Canal != 'Inválido') & (smp.Offset != 0) & (smp['Largura_Emissão(kHz)'] != '0')
smp[f]

,Num_Ato,Validade_RF,Fistel,Entidade,Número_Estação,Latitude,Longitude,Código_Município,UF,Potência(W),...,Frequência_Recepção,Largura_Emissão(kHz),Classe_Emissão,Multiplicidade,Início_Canal_Down,Fim_Canal_Down,Blocos_Downlink,Faixas,Intervalo_Canal,Offset
0,73832008,2023-12-15,50409428698,TIM S A,1058,-9.241111,-35.779472,2702801,AL,20.0,...,1735.0,200.0,G7W,5,1829.90,1830.10,1825.0-1830.0 | 1830.0-1835.0,1710-1880,Downlink,95.0
1,73832008,2023-12-15,50409428698,TIM S A,1058,-9.241111,-35.779472,2702801,AL,40.0,...,1735.0,10000.0,G7W,5,1825.00,1835.00,1825.0-1830.0 | 1830.0-1835.0,1710-1880,Downlink,95.0
2,73832008,2023-12-15,50409428698,TIM S A,1058,-9.241111,-35.779472,2702801,AL,40.0,...,829.5,5000.0,G9W,5,872.00,877.00,869.0-874.0 | 874.0-879.0,819-894,Downlink,45.0
3,73832008,2023-12-15,50409428698,TIM S A,1058,-9.241111,-35.779472,2702801,AL,40.0,...,829.5,10000.0,G7W,5,869.50,879.50,869.0-874.0 | 874.0-879.0 | 879.0-884.0,819-894,Downlink,45.0
4,97812014,2029-12-08,50409428698,TIM S A,1058,-9.241111,-35.779472,2702801,AL,40.0,...,723.0,10000.0,G7W,3,773.00,783.00,773.0-778.0 | 778.0-783.0,703-803,Downlink,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147550,46622011,2028-03-31,50409105090,CLARO S.A.,1015153167,-21.88574,-47.57269,3513702,SP,80.0,...,840.0,200.0,G7W,1,884.90,885.10,884.0-889.0,819-894,Downlink,45.0
147551,46622011,2028-03-31,50409105090,CLARO S.A.,1015153175,-22.30054,-47.80195,3523602,SP,80.0,...,847.75,2500.0,G7W,1,891.50,894.00,889.0-894.0,819-894,Downlink,45.0
147552,46622011,2028-03-31,50409105090,CLARO S.A.,1015153175,-22.30054,-47.80195,3523602,SP,80.0,...,840.0,200.0,G7W,1,884.90,885.10,884.0-889.0,819-894,Downlink,45.0
147553,46622011,2028-03-31,50409105090,CLARO S.A.,1015153175,-22.30054,-47.80195,3523602,SP,80.0,...,847.75,200.0,G7W,1,892.65,892.85,889.0-894.0,819-894,Downlink,45.0
147554,46622011,2028-03-31,50409105090,CLARO S.A.,1015153175,-22.30054,-47.80195,3523602,SP,80.0,...,840.0,10000.0,G7W,1,880.00,890.00,879.0-884.0 | 884.0-889.0 | 889.0-894.0,819-894,Downlink,45.0

In [ ]:
smp.loc[f, 'Frequência_Recepção_Teórica'] = smp.loc[f, 'Frequência_Transmissão'].astype('float') - smp.loc[f, 'Offset'].astype('float')

In [ ]:
(smp.Multiplicidade == 1).sum()

2608

In [ ]:
smp[smp.Frequência_Recepção_Teórica.isna()]

,Num_Ato,Validade_RF,Fistel,Entidade,Número_Estação,Latitude,Longitude,Código_Município,UF,Potência(W),...,Largura_Emissão(kHz),Classe_Emissão,Multiplicidade,Início_Canal_Down,Fim_Canal_Down,Blocos_Downlink,Faixas,Intervalo_Canal,Offset,Frequência_Recepção_Teórica
23,105802021,2038-04-30,50409146366,TELEFONICA BRASIL S.A.,3565,-32.03389,-52.09694,4315602,RS,200.0,...,100000.0,G7W,9,3400.0,3500.0,3400.0-3410.0 | 3410.0-3420.0 | 3420.0-3430.0 ...,3400-3410 | 3410-3420 | 3420-3430 | 3430-3440 ...,Downlink,0.0,NaN
109,105802021,2022-12-07,50409146447,TELEFONICA BRASIL S.A.,8605,-22.214036,-49.953528,3529005,SP,200.0,...,100000.0,G7W,19,3400.0,3500.0,3400.0-3410.0 | 3410.0-3420.0 | 3420.0-3430.0 ...,3400-3410 | 3410-3420 | 3420-3430 | 3430-3440 ...,Downlink,0.0,NaN
135,105802021,2041-12-08,50409146447,TELEFONICA BRASIL S.A.,8648,-22.125117,-51.387306,3541406,SP,200.0,...,100000.0,G7W,21,3400.0,3500.0,3400.0-3410.0 | 3410.0-3420.0 | 3420.0-3430.0 ...,3400-3410 | 3410-3420 | 3420-3430 | 3430-3440 ...,Downlink,0.0,NaN
147,105802021,2024-07-21,50409146366,TELEFONICA BRASIL S.A.,29874,-8.758906,-63.875331,1100205,RO,200.0,...,100000.0,G7W,42,3400.0,3500.0,3400.0-3410.0 | 3410.0-3420.0 | 3420.0-3430.0 ...,3400-3410 | 3410-3420 | 3420-3430 | 3430-3440 ...,Downlink,0.0,NaN
149,105812021.0,2041-12-08,50409428698,TIM S A,52086,-9.668861,-35.734806,2704302,AL,200.0,...,100000.0,G7W,144,3500.0,3600.0,3500.0-3510.0 | 3510.0-3520.0 | 3520.0-3530.0 ...,3500-3510 | 3510-3520 | 3520-3530 | 3530-3540 ...,Downlink,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147098,105742021,2041-12-08,50440366410,Brisanet Servicos de Telecomunicacoes S.A.,1015013900,-4.557036,-37.673945,2301109,CE,133.312,...,50000.0,G7W,16,2300.0,2350.0,2300.0-2305.0 | 2305.0-2310.0 | 2310.0-2315.0 ...,2300-2305 | 2305-2310 | 2310-2315 | 2315-2320 ...,Downlink,0.0,NaN
147099,43932023,2041-12-08,50440366410,Brisanet Servicos de Telecomunicacoes S.A.,1015013900,-4.557036,-37.673945,2301109,CE,53.312,...,20000.0,G7W,32,2360.0,2380.0,2360.0-2365.0 | 2365.0-2370.0 | 2370.0-2375.0 ...,2360-2365 | 2365-2370 | 2370-2375 | 2375-2380,Downlink,0.0,NaN
147181,105812021,2028-04-07,50409428698,TIM S A,1015029423,-14.279523,-38.996783,2914901,BA,200.0,...,100000.0,G7W,3,3500.0,3600.0,3500.0-3510.0 | 3510.0-3520.0 | 3520.0-3530.0 ...,3500-3510 | 3510-3520 | 3520-3530 | 3530-3540 ...,Downlink,0.0,NaN
147389,43932023,2041-12-08,50440366410,Brisanet Servicos de Telecomunicacoes S.A.,1015110620,-4.134481,-38.487991,2305233,CE,53.312,...,20000.0,G7W,28,2360.0,2380.0,2360.0-2365.0 | 2365.0-2370.0 | 2370.0-2375.0 ...,2360-2365 | 2365-2370 | 2370-2375 | 2375-2380,Downlink,0.0,NaN
147390,105742021,2041-12-08,50440366410,Brisanet Servicos de Telecomunicacoes S.A.,1015110620,-4.134481,-38.487991,2305233,CE,133.312,...,50000.0,G7W,14,2300.0,2350.0,2300.0-2305.0 | 2305.0-2310.0 | 2310.0-2315.0 ...,2300-2305 | 2305-2310 | 2310-2315 | 2315-2320 ...,Downlink,0.0,NaN

In [ ]:
# ibge = pd.read_excel(folder / 'municipios_coordenadas.xlsx', dtype='string')
ibge = pd.read_csv(folder.parent / 'extracao' / 'arquivos' / 'municipios_coordenadas.csv', dtype='string')

In [ ]:
ibge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   codigo_ibge  5570 non-null   string
 1   nome         5570 non-null   string
 2   latitude     5570 non-null   string
 3   longitude    5570 non-null   string
 4   capital      5570 non-null   string
 5   codigo_uf    5570 non-null   string
dtypes: string(6)
memory usage: 261.2 KB

In [ ]:
ibge.sample(5)

     codigo_ibge                 nome  latitude longitude capital codigo_uf
5050     3167301          Silveirânia  -21,1615  -43,2128       0        31
3775     3537800              Piedade  -23,7139  -47,4256       0        35
2621     3136652              Juatuba  -19,9448  -44,3451       0        31
5553     2933505  Wenceslau Guimarães  -13,6908  -39,4762       0        29
2929     3203320           Marataízes  -21,0398  -40,8384       0        32

In [ ]:
ibge.columns = ['Código_Município', 'Município', 'Latitude', 'Longitude', 'Capital', 'Código_UF']

Os dados que foram agregados por `['UF', 'Código_Município', 'Fistel', 'Frequência_Transmissão', 'Largura_Emissão(kHz)', 'Classe_Emissão']`. A coluna `Multiplicidade` guarda a contagem de estações agrupadas para dado conjunto de valores dessas colunas.

Para os registros que possuem `Multiplicidade=1`, não houve agregação e a estação é única. Para esses a coordenada da estação é mantida. Para todos os demais registros as coordenadas serão substituídas pela coordenada do município. Fazer processamento como imputar uma média das coordenadas não agrega valor "fiscalizatório" porque gera uma coordenada que não existe. A substituição pela coordenada central do município tem o propósito simplesmente de dar a localidade na qual aquele conjunto de estações serve.

In [ ]:
coords_municipio = pd.merge(smp.loc[smp.Multiplicidade != '1', 'Código_Município'], ibge[['Código_Município', 'Latitude', 'Longitude']], 
                            on='Código_Município', 
                            how='left')

In [ ]:
smp.loc[smp.Multiplicidade != '1', ['Latitude', 'Longitude']] = coords_municipio[['Latitude', 'Longitude']].values

In [ ]:
smp['Coords_Valida_IBGE'] = '1'

In [ ]:
smp.loc[smp.Multiplicidade != '1', 'Coords_Valida_IBGE'] = '0'

In [ ]:
smp[['Latitude_IBGE', 'Longitude_IBGE']] = smp[['Latitude', 'Longitude']]

In [ ]:
municipio = pd.merge(smp[['Código_Município']], ibge[['Código_Município', 'Município']], 
                            on='Código_Município', 
                            how='left')

In [ ]:
municipio[municipio.Município.isna()]

       Código_Município Município
126758        3530607        <NA>
126759        3530607        <NA>

In [ ]:
municipio.loc[municipio.Município.isna(), 'Município'] = 'Mogi das Cruzes'

In [ ]:
smp['Status'] = 'L'
smp['Num_Serviço'] = '010'

In [ ]:
smp['Município_IBGE'] = municipio.Município.values

In [ ]:
from extracao.format import merge_on_frequency, _filter_matlab, _format_matlab
from extracao.constants import COLUNAS

**Investigar esses casos abaixo!**

In [ ]:
smp[(smp.Intervalo_Canal != 'Inválido') & (smp['Largura_Emissão(kHz)'] == '0')][['Início_Canal_Down', 'Fim_Canal_Down', 'Frequência_Transmissão', 'Frequência_Recepção_Teórica']]

,Início_Canal_Down,Fim_Canal_Down,Frequência_Transmissão,Frequência_Recepção_Teórica
34921,892.75,892.75,892.75,NaN
34922,885.00,885.00,885.0,NaN
116939,874.50,874.50,874.5,NaN
139653,885.00,885.00,885.0,NaN
139654,885.00,885.00,885.0,NaN
139656,885.00,885.00,885.0,NaN

In [ ]:
smp['Tecnologia'] = smp.Tecnologia.str.strip()
smp.Tecnologia.unique()

<StringArray>
['GSM', 'LTE', 'WCDMA', 'NR', '', 'EDGE', 'CDMA', 'WCMDA', 'WDCMA']
Length: 9, dtype: string

In [ ]:
smp.Classe_Emissão.unique()

<StringArray>
['G7W', 'G9W', 'D7W', 'D9W', '0G7', 'G1D', 'G3E', 'F1D', 'DXW', 'F9W',  'NI',
 'M7W', 'F8W', 'GXW', 'G7E', 'F1W', 'F3E', 'D7D', 'OG7', 'F7W']
Length: 20, dtype: string

In [ ]:
f = smp.Tecnologia != ''
smp.loc[f, 'Classe_Emissão'] = smp.loc[f, 'Classe_Emissão'] + '-' + smp.loc[f, 'Tecnologia']

In [ ]:
down = smp.rename(columns={'Frequência_Transmissão' : 'Frequência'}).copy()
down = down.drop('Frequência_Recepção_Teórica', axis=1)

In [ ]:
down['Fonte'] = 'MOS'
down['Classe'] = 'FB'

Somente gerar frequência de `Uplink` para `Offset` e `Largura_Emissão(kHz)` != 0

In [ ]:
up = smp.rename(columns={'Frequência_Recepção_Teórica' : 'Frequência'}).copy()
up = up.drop('Frequência_Transmissão', axis=1)

In [ ]:
up[up.Frequência.notna()]

,Num_Ato,Validade_RF,Fistel,Entidade,Número_Estação,Latitude,Longitude,Código_Município,UF,Potência(W),...,Faixas,Intervalo_Canal,Offset,Frequência,Coords_Valida_IBGE,Latitude_IBGE,Longitude_IBGE,Status,Num_Serviço,Município_IBGE
0,73832008,2023-12-15,50409428698,TIM S A,1058,"-9,27281","-35,7139",2702801,AL,20.0,...,1710-1880,Downlink,95.0,1735.00,0,"-9,27281","-35,7139",L,010,Flexeiras
1,73832008,2023-12-15,50409428698,TIM S A,1058,"-9,27281","-35,7139",2702801,AL,40.0,...,1710-1880,Downlink,95.0,1735.00,0,"-9,27281","-35,7139",L,010,Flexeiras
2,73832008,2023-12-15,50409428698,TIM S A,1058,"-9,27281","-35,7139",2702801,AL,40.0,...,819-894,Downlink,45.0,829.50,0,"-9,27281","-35,7139",L,010,Flexeiras
3,73832008,2023-12-15,50409428698,TIM S A,1058,"-9,27281","-35,7139",2702801,AL,40.0,...,819-894,Downlink,45.0,829.50,0,"-9,27281","-35,7139",L,010,Flexeiras
4,97812014,2029-12-08,50409428698,TIM S A,1058,"-9,27281","-35,7139",2702801,AL,40.0,...,703-803,Downlink,55.0,723.00,0,"-9,27281","-35,7139",L,010,Flexeiras
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147550,46622011,2028-03-31,50409105090,CLARO S.A.,1015153167,"-21,9002","-47,6181",3513702,SP,80.0,...,819-894,Downlink,45.0,840.00,0,"-21,9002","-47,6181",L,010,Descalvado
147551,46622011,2028-03-31,50409105090,CLARO S.A.,1015153175,"-22,2562","-47,8166",3523602,SP,80.0,...,819-894,Downlink,45.0,847.75,0,"-22,2562","-47,8166",L,010,Itirapina
147552,46622011,2028-03-31,50409105090,CLARO S.A.,1015153175,"-22,2562","-47,8166",3523602,SP,80.0,...,819-894,Downlink,45.0,840.00,0,"-22,2562","-47,8166",L,010,Itirapina
147553,46622011,2028-03-31,50409105090,CLARO S.A.,1015153175,"-22,2562","-47,8166",3523602,SP,80.0,...,819-894,Downlink,45.0,847.75,0,"-22,2562","-47,8166",L,010,Itirapina
147554,46622011,2028-03-31,50409105090,CLARO S.A.,1015153175,"-22,2562","-47,8166",3523602,SP,80.0,...,819-894,Downlink,45.0,840.00,0,"-22,2562","-47,8166",L,010,Itirapina

In [ ]:
up.dropna(subset=['Frequência'], axis=0, inplace=True, ignore_index=True)
up.shape

(146058, 39)

In [ ]:
up['Fonte'] = 'DOC'
up['Classe'] = 'ML'

In [ ]:
smp = pd.concat([down, up], ignore_index=True)

In [ ]:
smp.shape

(293613, 41)

In [ ]:
df = _filter_matlab(smp.astype('string'))

In [ ]:
for c in ['Latitude', 'Longitude', 'Frequency']:
    df[c] = df[c].str.replace(',', '.')

In [ ]:
df = _format_matlab(df)

In [ ]:
df[df.Description.str.contains('*', regex=False)]

,Id,Frequency,Latitude,Longitude,Description,Service,Station,Class,BW
0,#1,454.5,-15.1100,-40.068401,"[DOC] L, ML, Claro S.A. (50409307637, 10026280...",10,1002628048,G7W-LTE,5000.0
1,#2,454.5,-15.0225,-42.372700,"[DOC] L, ML, Claro S.A. (50409307637, 10022640...",10,1002264003,G7W-LTE,5000.0
2,#3,454.5,-14.7678,-42.649799,"[DOC] L, ML, Claro S.A. (50409307637, 10021314...",10,1002131429,G7W-LTE,5000.0
3,#4,454.5,-14.5710,-42.943401,"[DOC] L, ML, Claro S.A. (50409307637, 10020029...",10,1002002904,G7W-LTE,5000.0
4,#5,454.5,-14.3847,-41.884201,"[DOC] L, ML, Claro S.A. (50409307637, 10022545...",10,1002254539,G7W-LTE,5000.0
...,...,...,...,...,...,...,...,...,...
293608,#293609,3640.0,-25.3902,-51.462299,"[MOS] L, FB, Ligga Telecomunicacoes S.A. (5044...",10,1015007195,D7W-NR,80000.0
293609,#293610,25400.0,-26.4851,-49.071301,"[MOS] L, FB, Claro S.A. (50409889580, 10131220...",10,1013122035,G7W-NR,100000.0
293610,#293611,25400.0,-23.5329,-46.639500,"[MOS] L, FB, Claro S.A. (50409105090, 10034121...",10,1003412162,G7W-NR,100000.0
293611,#293612,25600.0,-26.4851,-49.071301,"[MOS] L, FB, Claro S.A. (50409889580, 10131220...",10,1013122035,G7W-NR,100000.0
293612,#293613,25600.0,-23.5329,-46.639500,"[MOS] L, FB, Claro S.A. (50409105090, 10034121...",10,1003412162,G7W-NR,100000.0

In [ ]:
df.to_parquet(folder / 'smp_processado.parquet.gzip', compression='gzip')

In [ ]:
l = '[("Registro", ("Latitude", "Longitude")), ("Processamento", "Coordenadas do Município - Registros Agrupados")]'

In [ ]:
dict(eval(l))

{'Registro': ('Latitude', 'Longitude'),
 'Processamento': 'Coordenadas do Município - Registros Agrupados'}